set lines 100 pages 0 feedb off trims on
spool fvdesc.txt
prompt +++GO$SQL_BIND_CAPTURE+++
desc GO$SQL_BIND_CAPTURE

prompt +++GV$ACCESS+++
desc GV$ACCESS

prompt +++GV$ACTIVE_INSTANCES+++
desc GV$ACTIVE_INSTANCES

prompt +++GV$ACTIVE_SERVICES+++
desc GV$ACTIVE_SERVICES

prompt +++GV$ACTIVE_SESSION_HISTORY+++
desc GV$ACTIVE_SESSION_HISTORY

prompt +++GV$ACTIVE_SESS_POOL_MTH+++
desc GV$ACTIVE_SESS_POOL_MTH

prompt +++GV$ADVISOR_CURRENT_SQLPLAN+++
desc GV$ADVISOR_CURRENT_SQLPLAN

prompt +++GV$ADVISOR_PROGRESS+++
desc GV$ADVISOR_PROGRESS

prompt +++GV$ALERT_TYPES+++
desc GV$ALERT_TYPES

prompt +++GV$AQ1+++
desc GV$AQ1

prompt +++GV$AQ_BACKGROUND_COORDINATOR+++
desc GV$AQ_BACKGROUND_COORDINATOR

prompt +++GV$AQ_BMAP_NONDUR_SUBSCRIBERS+++
desc GV$AQ_BMAP_NONDUR_SUBSCRIBERS

prompt +++GV$AQ_CROSS_INSTANCE_JOBS+++
desc GV$AQ_CROSS_INSTANCE_JOBS

prompt +++GV$AQ_JOB_COORDINATOR+++
desc GV$AQ_JOB_COORDINATOR

prompt +++GV$AQ_MESSAGE_CACHE+++
desc GV$AQ_MESSAGE_CACHE

prompt +++GV$AQ_MSGBM+++
desc GV$AQ_MSGBM

prompt +++GV$AQ_NONDUR_REGISTRATIONS+++
desc GV$AQ_NONDUR_REGISTRATIONS

prompt +++GV$AQ_NONDUR_SUBSCRIBER+++
desc GV$AQ_NONDUR_SUBSCRIBER

prompt +++GV$AQ_NONDUR_SUBSCRIBER_LWM+++
desc GV$AQ_NONDUR_SUBSCRIBER_LWM

prompt +++GV$AQ_NOTIFICATION_CLIENTS+++
desc GV$AQ_NOTIFICATION_CLIENTS

prompt +++GV$AQ_SERVER_POOL+++
desc GV$AQ_SERVER_POOL

prompt +++GV$AQ_SUBSCRIBER_LOAD+++
desc GV$AQ_SUBSCRIBER_LOAD

prompt +++GV$ARCHIVE+++
desc GV$ARCHIVE

prompt +++GV$ARCHIVED_LOG+++
desc GV$ARCHIVED_LOG

prompt +++GV$ARCHIVE_DEST+++
desc GV$ARCHIVE_DEST

prompt +++GV$ARCHIVE_DEST_STATUS+++
desc GV$ARCHIVE_DEST_STATUS

prompt +++GV$ARCHIVE_GAP+++
desc GV$ARCHIVE_GAP

prompt +++GV$ARCHIVE_PROCESSES+++
desc GV$ARCHIVE_PROCESSES

prompt +++GV$ASH_INFO+++
desc GV$ASH_INFO

prompt +++GV$ASM_ACFSREPL+++
desc GV$ASM_ACFSREPL

prompt +++GV$ASM_ACFSREPLTAG+++
desc GV$ASM_ACFSREPLTAG

prompt +++GV$ASM_ACFSSNAPSHOTS+++
desc GV$ASM_ACFSSNAPSHOTS

prompt +++GV$ASM_ACFSTAG+++
desc GV$ASM_ACFSTAG

prompt +++GV$ASM_ACFSVOLUMES+++
desc GV$ASM_ACFSVOLUMES

prompt +++GV$ASM_ACFS_ENCRYPTION_INFO+++
desc GV$ASM_ACFS_ENCRYPTION_INFO

prompt +++GV$ASM_ACFS_SECURITY_INFO+++
desc GV$ASM_ACFS_SECURITY_INFO

prompt +++GV$ASM_ACFS_SEC_ADMIN+++
desc GV$ASM_ACFS_SEC_ADMIN

prompt +++GV$ASM_ACFS_SEC_CMDRULE+++
desc GV$ASM_ACFS_SEC_CMDRULE

prompt +++GV$ASM_ACFS_SEC_REALM+++
desc GV$ASM_ACFS_SEC_REALM

prompt +++GV$ASM_ACFS_SEC_REALM_FILTER+++
desc GV$ASM_ACFS_SEC_REALM_FILTER

prompt +++GV$ASM_ACFS_SEC_REALM_GROUP+++
desc GV$ASM_ACFS_SEC_REALM_GROUP

prompt +++GV$ASM_ACFS_SEC_REALM_USER+++
desc GV$ASM_ACFS_SEC_REALM_USER

prompt +++GV$ASM_ACFS_SEC_RULE+++
desc GV$ASM_ACFS_SEC_RULE

prompt +++GV$ASM_ACFS_SEC_RULESET+++
desc GV$ASM_ACFS_SEC_RULESET

prompt +++GV$ASM_ACFS_SEC_RULESET_RULE+++
desc GV$ASM_ACFS_SEC_RULESET_RULE

prompt +++GV$ASM_ALIAS+++
desc GV$ASM_ALIAS

prompt +++GV$ASM_ATTRIBUTE+++
desc GV$ASM_ATTRIBUTE

prompt +++GV$ASM_AUDIT_CLEANUP_JOBS+++
desc GV$ASM_AUDIT_CLEANUP_JOBS

prompt +++GV$ASM_AUDIT_CLEAN_EVENTS+++
desc GV$ASM_AUDIT_CLEAN_EVENTS

prompt +++GV$ASM_AUDIT_CONFIG_PARAMS+++
desc GV$ASM_AUDIT_CONFIG_PARAMS

prompt +++GV$ASM_AUDIT_LAST_ARCH_TS+++
desc GV$ASM_AUDIT_LAST_ARCH_TS

prompt +++GV$ASM_CLIENT+++
desc GV$ASM_CLIENT

prompt +++GV$ASM_DISK+++
desc GV$ASM_DISK

prompt +++GV$ASM_DISKGROUP+++
desc GV$ASM_DISKGROUP

prompt +++GV$ASM_DISKGROUP_SPARSE+++
desc GV$ASM_DISKGROUP_SPARSE

prompt +++GV$ASM_DISKGROUP_STAT+++
desc GV$ASM_DISKGROUP_STAT

prompt +++GV$ASM_DISK_IOSTAT+++
desc GV$ASM_DISK_IOSTAT

prompt +++GV$ASM_DISK_IOSTAT_SPARSE+++
desc GV$ASM_DISK_IOSTAT_SPARSE

prompt +++GV$ASM_DISK_SPARSE+++
desc GV$ASM_DISK_SPARSE

prompt +++GV$ASM_DISK_SPARSE_STAT+++
desc GV$ASM_DISK_SPARSE_STAT

prompt +++GV$ASM_DISK_STAT+++
desc GV$ASM_DISK_STAT

prompt +++GV$ASM_ESTIMATE+++
desc GV$ASM_ESTIMATE

prompt +++GV$ASM_FILE+++
desc GV$ASM_FILE

prompt +++GV$ASM_FILESYSTEM+++
desc GV$ASM_FILESYSTEM

prompt +++GV$ASM_OPERATION+++
desc GV$ASM_OPERATION

prompt +++GV$ASM_TEMPLATE+++
desc GV$ASM_TEMPLATE

prompt +++GV$ASM_USER+++
desc GV$ASM_USER

prompt +++GV$ASM_USERGROUP+++
desc GV$ASM_USERGROUP

prompt +++GV$ASM_USERGROUP_MEMBER+++
desc GV$ASM_USERGROUP_MEMBER

prompt +++GV$ASM_VOLUME+++
desc GV$ASM_VOLUME

prompt +++GV$ASM_VOLUME_STAT+++
desc GV$ASM_VOLUME_STAT

prompt +++GV$AUTO_BMR_STATISTICS+++
desc GV$AUTO_BMR_STATISTICS

prompt +++GV$AW_AGGREGATE_OP+++
desc GV$AW_AGGREGATE_OP

prompt +++GV$AW_ALLOCATE_OP+++
desc GV$AW_ALLOCATE_OP

prompt +++GV$AW_CALC+++
desc GV$AW_CALC

prompt +++GV$AW_LONGOPS+++
desc GV$AW_LONGOPS

prompt +++GV$AW_OLAP+++
desc GV$AW_OLAP

prompt +++GV$AW_SESSION_INFO+++
desc GV$AW_SESSION_INFO

prompt +++GV$BACKUP+++
desc GV$BACKUP

prompt +++GV$BACKUP_ASYNC_IO+++
desc GV$BACKUP_ASYNC_IO

prompt +++GV$BACKUP_COMPRESSION_PROGRESS+++
desc GV$BACKUP_COMPRESSION_PROGRESS

prompt +++GV$BACKUP_CORRUPTION+++
desc GV$BACKUP_CORRUPTION

prompt +++GV$BACKUP_DATAFILE+++
desc GV$BACKUP_DATAFILE

prompt +++GV$BACKUP_DEVICE+++
desc GV$BACKUP_DEVICE

prompt +++GV$BACKUP_NONLOGGED+++
desc GV$BACKUP_NONLOGGED

prompt +++GV$BACKUP_PIECE+++
desc GV$BACKUP_PIECE

prompt +++GV$BACKUP_REDOLOG+++
desc GV$BACKUP_REDOLOG

prompt +++GV$BACKUP_SET+++
desc GV$BACKUP_SET

prompt +++GV$BACKUP_SPFILE+++
desc GV$BACKUP_SPFILE

prompt +++GV$BACKUP_SYNC_IO+++
desc GV$BACKUP_SYNC_IO

prompt +++GV$BGPROCESS+++
desc GV$BGPROCESS

prompt +++GV$BH+++
desc GV$BH

prompt +++GV$BLOCKING_QUIESCE+++
desc GV$BLOCKING_QUIESCE

prompt +++GV$BSP+++
desc GV$BSP

prompt +++GV$BTS_STAT+++
desc GV$BTS_STAT

prompt +++GV$BT_SCAN_CACHE+++
desc GV$BT_SCAN_CACHE

prompt +++GV$BT_SCAN_OBJ_TEMPS+++
desc GV$BT_SCAN_OBJ_TEMPS

prompt +++GV$BUFFERED_PUBLISHERS+++
desc GV$BUFFERED_PUBLISHERS

prompt +++GV$BUFFERED_QUEUES+++
desc GV$BUFFERED_QUEUES

prompt +++GV$BUFFERED_SUBSCRIBERS+++
desc GV$BUFFERED_SUBSCRIBERS

prompt +++GV$BUFFER_POOL+++
desc GV$BUFFER_POOL

prompt +++GV$BUFFER_POOL_STATISTICS+++
desc GV$BUFFER_POOL_STATISTICS

prompt +++GV$CACHE+++
desc GV$CACHE

prompt +++GV$CACHE_LOCK+++
desc GV$CACHE_LOCK

prompt +++GV$CACHE_TRANSFER+++
desc GV$CACHE_TRANSFER

prompt +++GV$CALLTAG+++
desc GV$CALLTAG

prompt +++GV$CELL+++
desc GV$CELL

prompt +++GV$CELL_CONFIG+++
desc GV$CELL_CONFIG

prompt +++GV$CELL_CONFIG_INFO+++
desc GV$CELL_CONFIG_INFO

prompt +++GV$CELL_DB+++
desc GV$CELL_DB

prompt +++GV$CELL_DB_HISTORY+++
desc GV$CELL_DB_HISTORY

prompt +++GV$CELL_DISK+++
desc GV$CELL_DISK

prompt +++GV$CELL_DISK_HISTORY+++
desc GV$CELL_DISK_HISTORY

prompt +++GV$CELL_GLOBAL+++
desc GV$CELL_GLOBAL

prompt +++GV$CELL_GLOBAL_HISTORY+++
desc GV$CELL_GLOBAL_HISTORY

prompt +++GV$CELL_IOREASON+++
desc GV$CELL_IOREASON

prompt +++GV$CELL_IOREASON_NAME+++
desc GV$CELL_IOREASON_NAME

prompt +++GV$CELL_METRIC_DESC+++
desc GV$CELL_METRIC_DESC

prompt +++GV$CELL_OFL_THREAD_HISTORY+++
desc GV$CELL_OFL_THREAD_HISTORY

prompt +++GV$CELL_OPEN_ALERTS+++
desc GV$CELL_OPEN_ALERTS

prompt +++GV$CELL_REQUEST_TOTALS+++
desc GV$CELL_REQUEST_TOTALS

prompt +++GV$CELL_STATE+++
desc GV$CELL_STATE

prompt +++GV$CELL_THREAD_HISTORY+++
desc GV$CELL_THREAD_HISTORY

prompt +++GV$CHANNEL_WAITS+++
desc GV$CHANNEL_WAITS

prompt +++GV$CIRCUIT+++
desc GV$CIRCUIT

prompt +++GV$CLASS_CACHE_TRANSFER+++
desc GV$CLASS_CACHE_TRANSFER

prompt +++GV$CLASS_PING+++
desc GV$CLASS_PING

prompt +++GV$CLIENT_RESULT_CACHE_STATS+++
desc GV$CLIENT_RESULT_CACHE_STATS

prompt +++GV$CLIENT_SECRETS+++
desc GV$CLIENT_SECRETS

prompt +++GV$CLIENT_STATS+++
desc GV$CLIENT_STATS

prompt +++GV$CLONEDFILE+++
desc GV$CLONEDFILE

prompt +++GV$CLUSTER_INTERCONNECTS+++
desc GV$CLUSTER_INTERCONNECTS

prompt +++GV$CONFIGURED_INTERCONNECTS+++
desc GV$CONFIGURED_INTERCONNECTS

prompt +++GV$CONTAINERS+++
desc GV$CONTAINERS

prompt +++GV$CONTEXT+++
desc GV$CONTEXT

prompt +++GV$CONTROLFILE+++
desc GV$CONTROLFILE

prompt +++GV$CONTROLFILE_RECORD_SECTION+++
desc GV$CONTROLFILE_RECORD_SECTION

prompt +++GV$CON_SYSSTAT+++
desc GV$CON_SYSSTAT

prompt +++GV$CON_SYSTEM_EVENT+++
desc GV$CON_SYSTEM_EVENT

prompt +++GV$CON_SYSTEM_WAIT_CLASS+++
desc GV$CON_SYSTEM_WAIT_CLASS

prompt +++GV$CON_SYS_TIME_MODEL+++
desc GV$CON_SYS_TIME_MODEL

prompt +++GV$COPY_CORRUPTION+++
desc GV$COPY_CORRUPTION

prompt +++GV$COPY_NONLOGGED+++
desc GV$COPY_NONLOGGED

prompt +++GV$CORRUPT_XID_LIST+++
desc GV$CORRUPT_XID_LIST

prompt +++GV$CPOOL_CC_INFO+++
desc GV$CPOOL_CC_INFO

prompt +++GV$CPOOL_CC_STATS+++
desc GV$CPOOL_CC_STATS

prompt +++GV$CPOOL_CONN_INFO+++
desc GV$CPOOL_CONN_INFO

prompt +++GV$CPOOL_STATS+++
desc GV$CPOOL_STATS

prompt +++GV$CR_BLOCK_SERVER+++
desc GV$CR_BLOCK_SERVER

prompt +++GV$CURRENT_BLOCK_SERVER+++
desc GV$CURRENT_BLOCK_SERVER

prompt +++GV$DATABASE+++
desc GV$DATABASE

prompt +++GV$DATABASE_BLOCK_CORRUPTION+++
desc GV$DATABASE_BLOCK_CORRUPTION

prompt +++GV$DATABASE_INCARNATION+++
desc GV$DATABASE_INCARNATION

prompt +++GV$DATABASE_KEY_INFO+++
desc GV$DATABASE_KEY_INFO

prompt +++GV$DATAFILE+++
desc GV$DATAFILE

prompt +++GV$DATAFILE_COPY+++
desc GV$DATAFILE_COPY

prompt +++GV$DATAFILE_HEADER+++
desc GV$DATAFILE_HEADER

prompt +++GV$DATAGUARD_CONFIG+++
desc GV$DATAGUARD_CONFIG

prompt +++GV$DATAGUARD_STATS+++
desc GV$DATAGUARD_STATS

prompt +++GV$DATAGUARD_STATUS+++
desc GV$DATAGUARD_STATUS

prompt +++GV$DATAPUMP_JOB+++
desc GV$DATAPUMP_JOB

prompt +++GV$DATAPUMP_SESSION+++
desc GV$DATAPUMP_SESSION

prompt +++GV$DBFILE+++
desc GV$DBFILE

prompt +++GV$DBLINK+++
desc GV$DBLINK

prompt +++GV$DB_CACHE_ADVICE+++
desc GV$DB_CACHE_ADVICE

prompt +++GV$DB_OBJECT_CACHE+++
desc GV$DB_OBJECT_CACHE

prompt +++GV$DB_PIPES+++
desc GV$DB_PIPES

prompt +++GV$DB_TRANSPORTABLE_PLATFORM+++
desc GV$DB_TRANSPORTABLE_PLATFORM

prompt +++GV$DEAD_CLEANUP+++
desc GV$DEAD_CLEANUP

prompt +++GV$DELETED_OBJECT+++
desc GV$DELETED_OBJECT

prompt +++GV$DETACHED_SESSION+++
desc GV$DETACHED_SESSION

prompt +++GV$DG_BROKER_CONFIG+++
desc GV$DG_BROKER_CONFIG

prompt +++GV$DIAG_INFO+++
desc GV$DIAG_INFO

prompt +++GV$DISPATCHER+++
desc GV$DISPATCHER

prompt +++GV$DISPATCHER_CONFIG+++
desc GV$DISPATCHER_CONFIG

prompt +++GV$DISPATCHER_RATE+++
desc GV$DISPATCHER_RATE

prompt +++GV$DLM_ALL_LOCKS+++
desc GV$DLM_ALL_LOCKS

prompt +++GV$DLM_CONVERT_LOCAL+++
desc GV$DLM_CONVERT_LOCAL

prompt +++GV$DLM_CONVERT_REMOTE+++
desc GV$DLM_CONVERT_REMOTE

prompt +++GV$DLM_LATCH+++
desc GV$DLM_LATCH

prompt +++GV$DLM_LOCKS+++
desc GV$DLM_LOCKS

prompt +++GV$DLM_MISC+++
desc GV$DLM_MISC

prompt +++GV$DLM_RESS+++
desc GV$DLM_RESS

prompt +++GV$DLM_TRAFFIC_CONTROLLER+++
desc GV$DLM_TRAFFIC_CONTROLLER

prompt +++GV$DNFS_CHANNELS+++
desc GV$DNFS_CHANNELS

prompt +++GV$DNFS_FILES+++
desc GV$DNFS_FILES

prompt +++GV$DNFS_SERVERS+++
desc GV$DNFS_SERVERS

prompt +++GV$DNFS_STATS+++
desc GV$DNFS_STATS

prompt +++GV$DYNAMIC_REMASTER_STATS+++
desc GV$DYNAMIC_REMASTER_STATS

prompt +++GV$EDITIONABLE_TYPES+++
desc GV$EDITIONABLE_TYPES

prompt +++GV$EMON+++
desc GV$EMON

prompt +++GV$EMX_USAGE_STATS+++
desc GV$EMX_USAGE_STATS

prompt +++GV$ENABLEDPRIVS+++
desc GV$ENABLEDPRIVS

prompt +++GV$ENCRYPTED_TABLESPACES+++
desc GV$ENCRYPTED_TABLESPACES

prompt +++GV$ENCRYPTION_KEYS+++
desc GV$ENCRYPTION_KEYS

prompt +++GV$ENCRYPTION_WALLET+++
desc GV$ENCRYPTION_WALLET

prompt +++GV$ENQUEUE_LOCK+++
desc GV$ENQUEUE_LOCK

prompt +++GV$ENQUEUE_STAT+++
desc GV$ENQUEUE_STAT

prompt +++GV$ENQUEUE_STATISTICS+++
desc GV$ENQUEUE_STATISTICS

prompt +++GV$EVENTMETRIC+++
desc GV$EVENTMETRIC

prompt +++GV$EVENT_HISTOGRAM+++
desc GV$EVENT_HISTOGRAM

prompt +++GV$EVENT_HISTOGRAM_MICRO+++
desc GV$EVENT_HISTOGRAM_MICRO

prompt +++GV$EVENT_NAME+++
desc GV$EVENT_NAME

prompt +++GV$EXECUTION+++
desc GV$EXECUTION

prompt +++GV$FALSE_PING+++
desc GV$FALSE_PING

prompt +++GV$FAST_START_SERVERS+++
desc GV$FAST_START_SERVERS

prompt +++GV$FAST_START_TRANSACTIONS+++
desc GV$FAST_START_TRANSACTIONS

prompt +++GV$FILEMETRIC+++
desc GV$FILEMETRIC

prompt +++GV$FILEMETRIC_HISTORY+++
desc GV$FILEMETRIC_HISTORY

prompt +++GV$FILESPACE_USAGE+++
desc GV$FILESPACE_USAGE

prompt +++GV$FILESTAT+++
desc GV$FILESTAT

prompt +++GV$FILE_CACHE_TRANSFER+++
desc GV$FILE_CACHE_TRANSFER

prompt +++GV$FILE_HISTOGRAM+++
desc GV$FILE_HISTOGRAM

prompt +++GV$FILE_OPTIMIZED_HISTOGRAM+++
desc GV$FILE_OPTIMIZED_HISTOGRAM

prompt +++GV$FILE_PING+++
desc GV$FILE_PING

prompt +++GV$FIXED_TABLE+++
desc GV$FIXED_TABLE

prompt +++GV$FIXED_VIEW_DEFINITION+++
desc GV$FIXED_VIEW_DEFINITION

prompt +++GV$FLASHBACK_DATABASE_LOG+++
desc GV$FLASHBACK_DATABASE_LOG

prompt +++GV$FLASHBACK_DATABASE_LOGFILE+++
desc GV$FLASHBACK_DATABASE_LOGFILE

prompt +++GV$FLASHBACK_DATABASE_STAT+++
desc GV$FLASHBACK_DATABASE_STAT

prompt +++GV$FLASHFILESTAT+++
desc GV$FLASHFILESTAT

prompt +++GV$FOREIGN_ARCHIVED_LOG+++
desc GV$FOREIGN_ARCHIVED_LOG

prompt +++GV$FS_FAILOVER_HISTOGRAM+++
desc GV$FS_FAILOVER_HISTOGRAM

prompt +++GV$FS_FAILOVER_STATS+++
desc GV$FS_FAILOVER_STATS

prompt +++GV$FS_OBSERVER_HISTOGRAM+++
desc GV$FS_OBSERVER_HISTOGRAM

prompt +++GV$GCSHVMASTER_INFO+++
desc GV$GCSHVMASTER_INFO

prompt +++GV$GCSPFMASTER_INFO+++
desc GV$GCSPFMASTER_INFO

prompt +++GV$GC_ELEMENT+++
desc GV$GC_ELEMENT

prompt +++GV$GC_ELEMENTS_WITH_COLLISIONS+++
desc GV$GC_ELEMENTS_WITH_COLLISIONS

prompt +++GV$GES_BLOCKING_ENQUEUE+++
desc GV$GES_BLOCKING_ENQUEUE

prompt +++GV$GES_DEADLOCKS+++
desc GV$GES_DEADLOCKS

prompt +++GV$GES_DEADLOCK_SESSIONS+++
desc GV$GES_DEADLOCK_SESSIONS

prompt +++GV$GES_ENQUEUE+++
desc GV$GES_ENQUEUE

prompt +++GV$GG_APPLY_COORDINATOR+++
desc GV$GG_APPLY_COORDINATOR

prompt +++GV$GG_APPLY_READER+++
desc GV$GG_APPLY_READER

prompt +++GV$GG_APPLY_RECEIVER+++
desc GV$GG_APPLY_RECEIVER

prompt +++GV$GG_APPLY_SERVER+++
desc GV$GG_APPLY_SERVER

prompt +++GV$GLOBALCONTEXT+++
desc GV$GLOBALCONTEXT

prompt +++GV$GLOBAL_BLOCKED_LOCKS+++
desc GV$GLOBAL_BLOCKED_LOCKS

prompt +++GV$GLOBAL_TRANSACTION+++
desc GV$GLOBAL_TRANSACTION

prompt +++GV$GOLDENGATE_CAPABILITIES+++
desc GV$GOLDENGATE_CAPABILITIES

prompt +++GV$GOLDENGATE_CAPTURE+++
desc GV$GOLDENGATE_CAPTURE

prompt +++GV$GOLDENGATE_MESSAGE_TRACKING+++
desc GV$GOLDENGATE_MESSAGE_TRACKING

prompt +++GV$GOLDENGATE_TABLE_STATS+++
desc GV$GOLDENGATE_TABLE_STATS

prompt +++GV$GOLDENGATE_TRANSACTION+++
desc GV$GOLDENGATE_TRANSACTION

prompt +++GV$HANG_STATISTICS+++
desc GV$HANG_STATISTICS

prompt +++GV$HEAT_MAP_SEGMENT+++
desc GV$HEAT_MAP_SEGMENT

prompt +++GV$HM_CHECK+++
desc GV$HM_CHECK

prompt +++GV$HM_CHECK_PARAM+++
desc GV$HM_CHECK_PARAM

prompt +++GV$HM_FINDING+++
desc GV$HM_FINDING

prompt +++GV$HM_INFO+++
desc GV$HM_INFO

prompt +++GV$HM_RECOMMENDATION+++
desc GV$HM_RECOMMENDATION

prompt +++GV$HM_RUN+++
desc GV$HM_RUN

prompt +++GV$HS_AGENT+++
desc GV$HS_AGENT

prompt +++GV$HS_PARAMETER+++
desc GV$HS_PARAMETER

prompt +++GV$HS_SESSION+++
desc GV$HS_SESSION

prompt +++GV$HVMASTER_INFO+++
desc GV$HVMASTER_INFO

prompt +++GV$IM_COLUMN_LEVEL+++
desc GV$IM_COLUMN_LEVEL

prompt +++GV$IM_COL_CU+++
desc GV$IM_COL_CU

prompt +++GV$IM_HEADER+++
desc GV$IM_HEADER

prompt +++GV$IM_SEGMENTS+++
desc GV$IM_SEGMENTS

prompt +++GV$IM_SEGMENTS_DETAIL+++
desc GV$IM_SEGMENTS_DETAIL

prompt +++GV$IM_SEG_EXT_MAP+++
desc GV$IM_SEG_EXT_MAP

prompt +++GV$IM_SMU_CHUNK+++
desc GV$IM_SMU_CHUNK

prompt +++GV$IM_SMU_HEAD+++
desc GV$IM_SMU_HEAD

prompt +++GV$IM_TBS_EXT_MAP+++
desc GV$IM_TBS_EXT_MAP

prompt +++GV$IM_USER_SEGMENTS+++
desc GV$IM_USER_SEGMENTS

prompt +++GV$INCMETER_CONFIG+++
desc GV$INCMETER_CONFIG

prompt +++GV$INCMETER_INFO+++
desc GV$INCMETER_INFO

prompt +++GV$INCMETER_SUMMARY+++
desc GV$INCMETER_SUMMARY

prompt +++GV$INDEXED_FIXED_COLUMN+++
desc GV$INDEXED_FIXED_COLUMN

prompt +++GV$INMEMORY_AREA+++
desc GV$INMEMORY_AREA

prompt +++GV$INSTANCE+++
desc GV$INSTANCE

prompt +++GV$INSTANCE_CACHE_TRANSFER+++
desc GV$INSTANCE_CACHE_TRANSFER

prompt +++GV$INSTANCE_LOG_GROUP+++
desc GV$INSTANCE_LOG_GROUP

prompt +++GV$INSTANCE_PING+++
desc GV$INSTANCE_PING

prompt +++GV$INSTANCE_RECOVERY+++
desc GV$INSTANCE_RECOVERY

prompt +++GV$IOFUNCMETRIC+++
desc GV$IOFUNCMETRIC

prompt +++GV$IOFUNCMETRIC_HISTORY+++
desc GV$IOFUNCMETRIC_HISTORY

prompt +++GV$IOSTAT_CONSUMER_GROUP+++
desc GV$IOSTAT_CONSUMER_GROUP

prompt +++GV$IOSTAT_FILE+++
desc GV$IOSTAT_FILE

prompt +++GV$IOSTAT_FUNCTION+++
desc GV$IOSTAT_FUNCTION

prompt +++GV$IOSTAT_FUNCTION_DETAIL+++
desc GV$IOSTAT_FUNCTION_DETAIL

prompt +++GV$IOSTAT_NETWORK+++
desc GV$IOSTAT_NETWORK

prompt +++GV$IOS_CLIENT+++
desc GV$IOS_CLIENT

prompt +++GV$IO_CALIBRATION_STATUS+++
desc GV$IO_CALIBRATION_STATUS

prompt +++GV$IO_OUTLIER+++
desc GV$IO_OUTLIER

prompt +++GV$IR_FAILURE+++
desc GV$IR_FAILURE

prompt +++GV$IR_FAILURE_SET+++
desc GV$IR_FAILURE_SET

prompt +++GV$IR_MANUAL_CHECKLIST+++
desc GV$IR_MANUAL_CHECKLIST

prompt +++GV$IR_REPAIR+++
desc GV$IR_REPAIR

prompt +++GV$JAVAPOOL+++
desc GV$JAVAPOOL

prompt +++GV$JAVA_LIBRARY_CACHE_MEMORY+++
desc GV$JAVA_LIBRARY_CACHE_MEMORY

prompt +++GV$JAVA_POOL_ADVICE+++
desc GV$JAVA_POOL_ADVICE

prompt +++GV$KERNEL_IO_OUTLIER+++
desc GV$KERNEL_IO_OUTLIER

prompt +++GV$KEY_VECTOR+++
desc GV$KEY_VECTOR

prompt +++GV$KSFQP+++
desc GV$KSFQP

prompt +++GV$LATCH+++
desc GV$LATCH

prompt +++GV$LATCHHOLDER+++
desc GV$LATCHHOLDER

prompt +++GV$LATCHNAME+++
desc GV$LATCHNAME

prompt +++GV$LATCH_CHILDREN+++
desc GV$LATCH_CHILDREN

prompt +++GV$LATCH_MISSES+++
desc GV$LATCH_MISSES

prompt +++GV$LATCH_PARENT+++
desc GV$LATCH_PARENT

prompt +++GV$LGWRIO_OUTLIER+++
desc GV$LGWRIO_OUTLIER

prompt +++GV$LIBCACHE_LOCKS+++
desc GV$LIBCACHE_LOCKS

prompt +++GV$LIBRARYCACHE+++
desc GV$LIBRARYCACHE

prompt +++GV$LIBRARY_CACHE_MEMORY+++
desc GV$LIBRARY_CACHE_MEMORY

prompt +++GV$LICENSE+++
desc GV$LICENSE

prompt +++GV$LISTENER_NETWORK+++
desc GV$LISTENER_NETWORK

prompt +++GV$LOADISTAT+++
desc GV$LOADISTAT

prompt +++GV$LOADPSTAT+++
desc GV$LOADPSTAT

prompt +++GV$LOBSTAT+++
desc GV$LOBSTAT

prompt +++GV$LOCK+++
desc GV$LOCK

prompt +++GV$LOCKED_OBJECT+++
desc GV$LOCKED_OBJECT

prompt +++GV$LOCKS_WITH_COLLISIONS+++
desc GV$LOCKS_WITH_COLLISIONS

prompt +++GV$LOCK_ACTIVITY+++
desc GV$LOCK_ACTIVITY

prompt +++GV$LOCK_ELEMENT+++
desc GV$LOCK_ELEMENT

prompt +++GV$LOCK_TYPE+++
desc GV$LOCK_TYPE

prompt +++GV$LOG+++
desc GV$LOG

prompt +++GV$LOGFILE+++
desc GV$LOGFILE

prompt +++GV$LOGHIST+++
desc GV$LOGHIST

prompt +++GV$LOGMNR_CONTENTS+++
desc GV$LOGMNR_CONTENTS

prompt +++GV$LOGMNR_DBA_OBJECTS+++
desc GV$LOGMNR_DBA_OBJECTS

prompt +++GV$LOGMNR_DICTIONARY+++
desc GV$LOGMNR_DICTIONARY

prompt +++GV$LOGMNR_DICTIONARY_LOAD+++
desc GV$LOGMNR_DICTIONARY_LOAD

prompt +++GV$LOGMNR_EXTENTS+++
desc GV$LOGMNR_EXTENTS

prompt +++GV$LOGMNR_LATCH+++
desc GV$LOGMNR_LATCH

prompt +++GV$LOGMNR_LOGFILE+++
desc GV$LOGMNR_LOGFILE

prompt +++GV$LOGMNR_LOGS+++
desc GV$LOGMNR_LOGS

prompt +++GV$LOGMNR_OBJECT_SEGMENTS+++
desc GV$LOGMNR_OBJECT_SEGMENTS

prompt +++GV$LOGMNR_PARAMETERS+++
desc GV$LOGMNR_PARAMETERS

prompt +++GV$LOGMNR_PROCESS+++
desc GV$LOGMNR_PROCESS

prompt +++GV$LOGMNR_SESSION+++
desc GV$LOGMNR_SESSION

prompt +++GV$LOGMNR_STATS+++
desc GV$LOGMNR_STATS

prompt +++GV$LOGMNR_SYS_DBA_SEGS+++
desc GV$LOGMNR_SYS_DBA_SEGS

prompt +++GV$LOGMNR_SYS_OBJECTS+++
desc GV$LOGMNR_SYS_OBJECTS

prompt +++GV$LOGMNR_TRANSACTION+++
desc GV$LOGMNR_TRANSACTION

prompt +++GV$LOGSTDBY+++
desc GV$LOGSTDBY

prompt +++GV$LOGSTDBY_PROCESS+++
desc GV$LOGSTDBY_PROCESS

prompt +++GV$LOGSTDBY_PROGRESS+++
desc GV$LOGSTDBY_PROGRESS

prompt +++GV$LOGSTDBY_STATE+++
desc GV$LOGSTDBY_STATE

prompt +++GV$LOGSTDBY_STATS+++
desc GV$LOGSTDBY_STATS

prompt +++GV$LOGSTDBY_TRANSACTION+++
desc GV$LOGSTDBY_TRANSACTION

prompt +++GV$LOG_HISTORY+++
desc GV$LOG_HISTORY

prompt +++GV$MANAGED_STANDBY+++
desc GV$MANAGED_STANDBY

prompt +++GV$MAPPED_SQL+++
desc GV$MAPPED_SQL

prompt +++GV$MAP_COMP_LIST+++
desc GV$MAP_COMP_LIST

prompt +++GV$MAP_ELEMENT+++
desc GV$MAP_ELEMENT

prompt +++GV$MAP_EXT_ELEMENT+++
desc GV$MAP_EXT_ELEMENT

prompt +++GV$MAP_FILE+++
desc GV$MAP_FILE

prompt +++GV$MAP_FILE_EXTENT+++
desc GV$MAP_FILE_EXTENT

prompt +++GV$MAP_FILE_IO_STACK+++
desc GV$MAP_FILE_IO_STACK

prompt +++GV$MAP_LIBRARY+++
desc GV$MAP_LIBRARY

prompt +++GV$MAP_SUBELEMENT+++
desc GV$MAP_SUBELEMENT

prompt +++GV$MAX_ACTIVE_SESS_TARGET_MTH+++
desc GV$MAX_ACTIVE_SESS_TARGET_MTH

prompt +++GV$MEMORY_CURRENT_RESIZE_OPS+++
desc GV$MEMORY_CURRENT_RESIZE_OPS

prompt +++GV$MEMORY_DYNAMIC_COMPONENTS+++
desc GV$MEMORY_DYNAMIC_COMPONENTS

prompt +++GV$MEMORY_RESIZE_OPS+++
desc GV$MEMORY_RESIZE_OPS

prompt +++GV$MEMORY_TARGET_ADVICE+++
desc GV$MEMORY_TARGET_ADVICE

prompt +++GV$METRIC+++
desc GV$METRIC

prompt +++GV$METRICGROUP+++
desc GV$METRICGROUP

prompt +++GV$METRICNAME+++
desc GV$METRICNAME

prompt +++GV$METRIC_HISTORY+++
desc GV$METRIC_HISTORY

prompt +++GV$MTTR_TARGET_ADVICE+++
desc GV$MTTR_TARGET_ADVICE

prompt +++GV$MUTEX_SLEEP+++
desc GV$MUTEX_SLEEP

prompt +++GV$MUTEX_SLEEP_HISTORY+++
desc GV$MUTEX_SLEEP_HISTORY

prompt +++GV$MVREFRESH+++
desc GV$MVREFRESH

prompt +++GV$MYSTAT+++
desc GV$MYSTAT

prompt +++GV$NFS_CLIENTS+++
desc GV$NFS_CLIENTS

prompt +++GV$NFS_LOCKS+++
desc GV$NFS_LOCKS

prompt +++GV$NFS_OPEN_FILES+++
desc GV$NFS_OPEN_FILES

prompt +++GV$NLS_PARAMETERS+++
desc GV$NLS_PARAMETERS

prompt +++GV$NLS_VALID_VALUES+++
desc GV$NLS_VALID_VALUES

prompt +++GV$NONLOGGED_BLOCK+++
desc GV$NONLOGGED_BLOCK

prompt +++GV$OBJECT_DEPENDENCY+++
desc GV$OBJECT_DEPENDENCY

prompt +++GV$OBJECT_DML_FREQUENCIES+++
desc GV$OBJECT_DML_FREQUENCIES

prompt +++GV$OBSOLETE_PARAMETER+++
desc GV$OBSOLETE_PARAMETER

prompt +++GV$OFFLINE_RANGE+++
desc GV$OFFLINE_RANGE

prompt +++GV$OFSMOUNT+++
desc GV$OFSMOUNT

prompt +++GV$OFS_STATS+++
desc GV$OFS_STATS

prompt +++GV$OPEN_CURSOR+++
desc GV$OPEN_CURSOR

prompt +++GV$OPTIMIZER_PROCESSING_RATE+++
desc GV$OPTIMIZER_PROCESSING_RATE

prompt +++GV$OPTION+++
desc GV$OPTION

prompt +++GV$OSSTAT+++
desc GV$OSSTAT

prompt +++GV$PARALLEL_DEGREE_LIMIT_MTH+++
desc GV$PARALLEL_DEGREE_LIMIT_MTH

prompt +++GV$PARAMETER+++
desc GV$PARAMETER

prompt +++GV$PARAMETER2+++
desc GV$PARAMETER2

prompt +++GV$PARAMETER_VALID_VALUES+++
desc GV$PARAMETER_VALID_VALUES

prompt +++GV$PATCHES+++
desc GV$PATCHES

prompt +++GV$PDBS+++
desc GV$PDBS

prompt +++GV$PDB_INCARNATION+++
desc GV$PDB_INCARNATION

prompt +++GV$PERSISTENT_PUBLISHERS+++
desc GV$PERSISTENT_PUBLISHERS

prompt +++GV$PERSISTENT_QMN_CACHE+++
desc GV$PERSISTENT_QMN_CACHE

prompt +++GV$PERSISTENT_QUEUES+++
desc GV$PERSISTENT_QUEUES

prompt +++GV$PERSISTENT_SUBSCRIBERS+++
desc GV$PERSISTENT_SUBSCRIBERS

prompt +++GV$PGASTAT+++
desc GV$PGASTAT

prompt +++GV$PGA_TARGET_ADVICE+++
desc GV$PGA_TARGET_ADVICE

prompt +++GV$PGA_TARGET_ADVICE_HISTOGRAM+++
desc GV$PGA_TARGET_ADVICE_HISTOGRAM

prompt +++GV$PING+++
desc GV$PING

prompt +++GV$POLICY_HISTORY+++
desc GV$POLICY_HISTORY

prompt +++GV$PQ_SESSTAT+++
desc GV$PQ_SESSTAT

prompt +++GV$PQ_SLAVE+++
desc GV$PQ_SLAVE

prompt +++GV$PQ_SYSSTAT+++
desc GV$PQ_SYSSTAT

prompt +++GV$PQ_TQSTAT+++
desc GV$PQ_TQSTAT

prompt +++GV$PROCESS+++
desc GV$PROCESS

prompt +++GV$PROCESS_GROUP+++
desc GV$PROCESS_GROUP

prompt +++GV$PROCESS_MEMORY+++
desc GV$PROCESS_MEMORY

prompt +++GV$PROCESS_MEMORY_DETAIL+++
desc GV$PROCESS_MEMORY_DETAIL

prompt +++GV$PROCESS_MEMORY_DETAIL_PROG+++
desc GV$PROCESS_MEMORY_DETAIL_PROG

prompt +++GV$PROPAGATION_RECEIVER+++
desc GV$PROPAGATION_RECEIVER

prompt +++GV$PROPAGATION_SENDER+++
desc GV$PROPAGATION_SENDER

prompt +++GV$PROXY_ARCHIVEDLOG+++
desc GV$PROXY_ARCHIVEDLOG

prompt +++GV$PROXY_DATAFILE+++
desc GV$PROXY_DATAFILE

prompt +++GV$PWFILE_USERS+++
desc GV$PWFILE_USERS

prompt +++GV$PX_BUFFER_ADVICE+++
desc GV$PX_BUFFER_ADVICE

prompt +++GV$PX_INSTANCE_GROUP+++
desc GV$PX_INSTANCE_GROUP

prompt +++GV$PX_PROCESS+++
desc GV$PX_PROCESS

prompt +++GV$PX_PROCESS_SYSSTAT+++
desc GV$PX_PROCESS_SYSSTAT

prompt +++GV$PX_PROCESS_TRACE+++
desc GV$PX_PROCESS_TRACE

prompt +++GV$PX_SESSION+++
desc GV$PX_SESSION

prompt +++GV$PX_SESSTAT+++
desc GV$PX_SESSTAT

prompt +++GV$QMON_COORDINATOR_STATS+++
desc GV$QMON_COORDINATOR_STATS

prompt +++GV$QMON_SERVER_STATS+++
desc GV$QMON_SERVER_STATS

prompt +++GV$QMON_TASKS+++
desc GV$QMON_TASKS

prompt +++GV$QMON_TASK_STATS+++
desc GV$QMON_TASK_STATS

prompt +++GV$QPX_INVENTORY+++
desc GV$QPX_INVENTORY

prompt +++GV$QUEUE+++
desc GV$QUEUE

prompt +++GV$QUEUEING_MTH+++
desc GV$QUEUEING_MTH

prompt +++GV$RECOVERY_FILE_STATUS+++
desc GV$RECOVERY_FILE_STATUS

prompt +++GV$RECOVERY_LOG+++
desc GV$RECOVERY_LOG

prompt +++GV$RECOVERY_PROGRESS+++
desc GV$RECOVERY_PROGRESS

prompt +++GV$RECOVERY_STATUS+++
desc GV$RECOVERY_STATUS

prompt +++GV$RECOVER_FILE+++
desc GV$RECOVER_FILE

prompt +++GV$REDO_DEST_RESP_HISTOGRAM+++
desc GV$REDO_DEST_RESP_HISTOGRAM

prompt +++GV$REPLAY_CONTEXT+++
desc GV$REPLAY_CONTEXT

prompt +++GV$REPLAY_CONTEXT_LOB+++
desc GV$REPLAY_CONTEXT_LOB

prompt +++GV$REPLAY_CONTEXT_SEQUENCE+++
desc GV$REPLAY_CONTEXT_SEQUENCE

prompt +++GV$REPLAY_CONTEXT_SYSDATE+++
desc GV$REPLAY_CONTEXT_SYSDATE

prompt +++GV$REPLAY_CONTEXT_SYSGUID+++
desc GV$REPLAY_CONTEXT_SYSGUID

prompt +++GV$REPLAY_CONTEXT_SYSTIMESTAMP+++
desc GV$REPLAY_CONTEXT_SYSTIMESTAMP

prompt +++GV$REPLPROP+++
desc GV$REPLPROP

prompt +++GV$REPLQUEUE+++
desc GV$REPLQUEUE

prompt +++GV$REQDIST+++
desc GV$REQDIST

prompt +++GV$RESERVED_WORDS+++
desc GV$RESERVED_WORDS

prompt +++GV$RESOURCE+++
desc GV$RESOURCE

prompt +++GV$RESOURCE_LIMIT+++
desc GV$RESOURCE_LIMIT

prompt +++GV$RESTORE_POINT+++
desc GV$RESTORE_POINT

prompt +++GV$RESULT_CACHE_DEPENDENCY+++
desc GV$RESULT_CACHE_DEPENDENCY

prompt +++GV$RESULT_CACHE_DR+++
desc GV$RESULT_CACHE_DR

prompt +++GV$RESULT_CACHE_MEMORY+++
desc GV$RESULT_CACHE_MEMORY

prompt +++GV$RESULT_CACHE_OBJECTS+++
desc GV$RESULT_CACHE_OBJECTS

prompt +++GV$RESULT_CACHE_RD+++
desc GV$RESULT_CACHE_RD

prompt +++GV$RESULT_CACHE_RR+++
desc GV$RESULT_CACHE_RR

prompt +++GV$RESULT_CACHE_STATISTICS+++
desc GV$RESULT_CACHE_STATISTICS

prompt +++GV$RESUMABLE+++
desc GV$RESUMABLE

prompt +++GV$RFS_THREAD+++
desc GV$RFS_THREAD

prompt +++GV$RMAN_COMPRESSION_ALGORITHM+++
desc GV$RMAN_COMPRESSION_ALGORITHM

prompt +++GV$RMAN_CONFIGURATION+++
desc GV$RMAN_CONFIGURATION

prompt +++GV$RMAN_ENCRYPTION_ALGORITHMS+++
desc GV$RMAN_ENCRYPTION_ALGORITHMS

prompt +++GV$RMAN_OUTPUT+++
desc GV$RMAN_OUTPUT

prompt +++GV$RMAN_STATUS_CURRENT+++
desc GV$RMAN_STATUS_CURRENT

prompt +++GV$ROLLSTAT+++
desc GV$ROLLSTAT

prompt +++GV$ROWCACHE+++
desc GV$ROWCACHE

prompt +++GV$ROWCACHE_PARENT+++
desc GV$ROWCACHE_PARENT

prompt +++GV$ROWCACHE_SUBORDINATE+++
desc GV$ROWCACHE_SUBORDINATE

prompt +++GV$RO_USER_ACCOUNT+++
desc GV$RO_USER_ACCOUNT

prompt +++GV$RSRCMGRMETRIC+++
desc GV$RSRCMGRMETRIC

prompt +++GV$RSRCMGRMETRIC_HISTORY+++
desc GV$RSRCMGRMETRIC_HISTORY

prompt +++GV$RSRC_CONSUMER_GROUP+++
desc GV$RSRC_CONSUMER_GROUP

prompt +++GV$RSRC_CONSUMER_GROUP_CPU_MTH+++
desc GV$RSRC_CONSUMER_GROUP_CPU_MTH

prompt +++GV$RSRC_CONS_GROUP_HISTORY+++
desc GV$RSRC_CONS_GROUP_HISTORY

prompt +++GV$RSRC_PLAN+++
desc GV$RSRC_PLAN

prompt +++GV$RSRC_PLAN_CPU_MTH+++
desc GV$RSRC_PLAN_CPU_MTH

prompt +++GV$RSRC_PLAN_HISTORY+++
desc GV$RSRC_PLAN_HISTORY

prompt +++GV$RSRC_SESSION_INFO+++
desc GV$RSRC_SESSION_INFO

prompt +++GV$RT_ADDM_CONTROL+++
desc GV$RT_ADDM_CONTROL

prompt +++GV$RULE+++
desc GV$RULE

prompt +++GV$RULE_SET+++
desc GV$RULE_SET

prompt +++GV$RULE_SET_AGGREGATE_STATS+++
desc GV$RULE_SET_AGGREGATE_STATS

prompt +++GV$SCHEDULER_INMEM_MDINFO+++
desc GV$SCHEDULER_INMEM_MDINFO

prompt +++GV$SCHEDULER_INMEM_RTINFO+++
desc GV$SCHEDULER_INMEM_RTINFO

prompt +++GV$SCHEDULER_RUNNING_JOBS+++
desc GV$SCHEDULER_RUNNING_JOBS

prompt +++GV$SECUREFILE_TIMER+++
desc GV$SECUREFILE_TIMER

prompt +++GV$SEGMENT_STATISTICS+++
desc GV$SEGMENT_STATISTICS

prompt +++GV$SEGSPACE_USAGE+++
desc GV$SEGSPACE_USAGE

prompt +++GV$SEGSTAT+++
desc GV$SEGSTAT

prompt +++GV$SEGSTAT_NAME+++
desc GV$SEGSTAT_NAME

prompt +++GV$SERVICEMETRIC+++
desc GV$SERVICEMETRIC

prompt +++GV$SERVICEMETRIC_HISTORY+++
desc GV$SERVICEMETRIC_HISTORY

prompt +++GV$SERVICES+++
desc GV$SERVICES

prompt +++GV$SERVICE_EVENT+++
desc GV$SERVICE_EVENT

prompt +++GV$SERVICE_STATS+++
desc GV$SERVICE_STATS

prompt +++GV$SERVICE_WAIT_CLASS+++
desc GV$SERVICE_WAIT_CLASS

prompt +++GV$SERV_MOD_ACT_STATS+++
desc GV$SERV_MOD_ACT_STATS

prompt +++GV$SESSION+++
desc GV$SESSION

prompt +++GV$SESSIONS_COUNT+++
desc GV$SESSIONS_COUNT

prompt +++GV$SESSION_BLOCKERS+++
desc GV$SESSION_BLOCKERS

prompt +++GV$SESSION_CLIENT_RESULT_CACHE+++
desc GV$SESSION_CLIENT_RESULT_CACHE

prompt +++GV$SESSION_CONNECT_INFO+++
desc GV$SESSION_CONNECT_INFO

prompt +++GV$SESSION_CURSOR_CACHE+++
desc GV$SESSION_CURSOR_CACHE

prompt +++GV$SESSION_EVENT+++
desc GV$SESSION_EVENT

prompt +++GV$SESSION_FIX_CONTROL+++
desc GV$SESSION_FIX_CONTROL

prompt +++GV$SESSION_LONGOPS+++
desc GV$SESSION_LONGOPS

prompt +++GV$SESSION_OBJECT_CACHE+++
desc GV$SESSION_OBJECT_CACHE

prompt +++GV$SESSION_WAIT+++
desc GV$SESSION_WAIT

prompt +++GV$SESSION_WAIT_CLASS+++
desc GV$SESSION_WAIT_CLASS

prompt +++GV$SESSION_WAIT_HISTORY+++
desc GV$SESSION_WAIT_HISTORY

prompt +++GV$SESSMETRIC+++
desc GV$SESSMETRIC

prompt +++GV$SESSTAT+++
desc GV$SESSTAT

prompt +++GV$SESS_IO+++
desc GV$SESS_IO

prompt +++GV$SESS_TIME_MODEL+++
desc GV$SESS_TIME_MODEL

prompt +++GV$SES_OPTIMIZER_ENV+++
desc GV$SES_OPTIMIZER_ENV

prompt +++GV$SGA+++
desc GV$SGA

prompt +++GV$SGAINFO+++
desc GV$SGAINFO

prompt +++GV$SGASTAT+++
desc GV$SGASTAT

prompt +++GV$SGA_CURRENT_RESIZE_OPS+++
desc GV$SGA_CURRENT_RESIZE_OPS

prompt +++GV$SGA_DYNAMIC_COMPONENTS+++
desc GV$SGA_DYNAMIC_COMPONENTS

prompt +++GV$SGA_DYNAMIC_FREE_MEMORY+++
desc GV$SGA_DYNAMIC_FREE_MEMORY

prompt +++GV$SGA_RESIZE_OPS+++
desc GV$SGA_RESIZE_OPS

prompt +++GV$SGA_TARGET_ADVICE+++
desc GV$SGA_TARGET_ADVICE

prompt +++GV$SHARED_POOL_ADVICE+++
desc GV$SHARED_POOL_ADVICE

prompt +++GV$SHARED_POOL_RESERVED+++
desc GV$SHARED_POOL_RESERVED

prompt +++GV$SHARED_SERVER+++
desc GV$SHARED_SERVER

prompt +++GV$SHARED_SERVER_MONITOR+++
desc GV$SHARED_SERVER_MONITOR

prompt +++GV$SORT_SEGMENT+++
desc GV$SORT_SEGMENT

prompt +++GV$SORT_USAGE+++
desc GV$SORT_USAGE

prompt +++GV$SPPARAMETER+++
desc GV$SPPARAMETER

prompt +++GV$SQL+++
desc GV$SQL

prompt +++GV$SQLAREA+++
desc GV$SQLAREA

prompt +++GV$SQLAREA_PLAN_HASH+++
desc GV$SQLAREA_PLAN_HASH

prompt +++GV$SQLCOMMAND+++
desc GV$SQLCOMMAND

prompt +++GV$SQLFN_ARG_METADATA+++
desc GV$SQLFN_ARG_METADATA

prompt +++GV$SQLFN_METADATA+++
desc GV$SQLFN_METADATA

prompt +++GV$SQLPA_METRIC+++
desc GV$SQLPA_METRIC

prompt +++GV$SQLSTATS+++
desc GV$SQLSTATS

prompt +++GV$SQLSTATS_PLAN_HASH+++
desc GV$SQLSTATS_PLAN_HASH

prompt +++GV$SQLTEXT+++
desc GV$SQLTEXT

prompt +++GV$SQLTEXT_WITH_NEWLINES+++
desc GV$SQLTEXT_WITH_NEWLINES

prompt +++GV$SQL_BIND_DATA+++
desc GV$SQL_BIND_DATA

prompt +++GV$SQL_BIND_METADATA+++
desc GV$SQL_BIND_METADATA

prompt +++GV$SQL_CS_HISTOGRAM+++
desc GV$SQL_CS_HISTOGRAM

prompt +++GV$SQL_CS_SELECTIVITY+++
desc GV$SQL_CS_SELECTIVITY

prompt +++GV$SQL_CS_STATISTICS+++
desc GV$SQL_CS_STATISTICS

prompt +++GV$SQL_CURSOR+++
desc GV$SQL_CURSOR

prompt +++GV$SQL_DIAG_REPOSITORY+++
desc GV$SQL_DIAG_REPOSITORY

prompt +++GV$SQL_DIAG_REPOSITORY_REASON+++
desc GV$SQL_DIAG_REPOSITORY_REASON

prompt +++GV$SQL_FEATURE+++
desc GV$SQL_FEATURE

prompt +++GV$SQL_FEATURE_DEPENDENCY+++
desc GV$SQL_FEATURE_DEPENDENCY

prompt +++GV$SQL_FEATURE_HIERARCHY+++
desc GV$SQL_FEATURE_HIERARCHY

prompt +++GV$SQL_HINT+++
desc GV$SQL_HINT

prompt +++GV$SQL_JOIN_FILTER+++
desc GV$SQL_JOIN_FILTER

prompt +++GV$SQL_MONITOR+++
desc GV$SQL_MONITOR

prompt +++GV$SQL_MONITOR_SESSTAT+++
desc GV$SQL_MONITOR_SESSTAT

prompt +++GV$SQL_MONITOR_STATNAME+++
desc GV$SQL_MONITOR_STATNAME

prompt +++GV$SQL_OPTIMIZER_ENV+++
desc GV$SQL_OPTIMIZER_ENV

prompt +++GV$SQL_PLAN+++
desc GV$SQL_PLAN

prompt +++GV$SQL_PLAN_MONITOR+++
desc GV$SQL_PLAN_MONITOR

prompt +++GV$SQL_PLAN_STATISTICS+++
desc GV$SQL_PLAN_STATISTICS

prompt +++GV$SQL_PLAN_STATISTICS_ALL+++
desc GV$SQL_PLAN_STATISTICS_ALL

prompt +++GV$SQL_REDIRECTION+++
desc GV$SQL_REDIRECTION

prompt +++GV$SQL_REOPTIMIZATION_HINTS+++
desc GV$SQL_REOPTIMIZATION_HINTS

prompt +++GV$SQL_SHARED_CURSOR+++
desc GV$SQL_SHARED_CURSOR

prompt +++GV$SQL_SHARED_MEMORY+++
desc GV$SQL_SHARED_MEMORY

prompt +++GV$SQL_WORKAREA+++
desc GV$SQL_WORKAREA

prompt +++GV$SQL_WORKAREA_ACTIVE+++
desc GV$SQL_WORKAREA_ACTIVE

prompt +++GV$SQL_WORKAREA_HISTOGRAM+++
desc GV$SQL_WORKAREA_HISTOGRAM

prompt +++GV$SSCR_SESSIONS+++
desc GV$SSCR_SESSIONS

prompt +++GV$STANDBY_LOG+++
desc GV$STANDBY_LOG

prompt +++GV$STATISTICS_LEVEL+++
desc GV$STATISTICS_LEVEL

prompt +++GV$STATNAME+++
desc GV$STATNAME

prompt +++GV$STREAMS_APPLY_COORDINATOR+++
desc GV$STREAMS_APPLY_COORDINATOR

prompt +++GV$STREAMS_APPLY_READER+++
desc GV$STREAMS_APPLY_READER

prompt +++GV$STREAMS_APPLY_SERVER+++
desc GV$STREAMS_APPLY_SERVER

prompt +++GV$STREAMS_CAPTURE+++
desc GV$STREAMS_CAPTURE

prompt +++GV$STREAMS_MESSAGE_TRACKING+++
desc GV$STREAMS_MESSAGE_TRACKING

prompt +++GV$STREAMS_POOL_ADVICE+++
desc GV$STREAMS_POOL_ADVICE

prompt +++GV$STREAMS_POOL_STATISTICS+++
desc GV$STREAMS_POOL_STATISTICS

prompt +++GV$STREAMS_TRANSACTION+++
desc GV$STREAMS_TRANSACTION

prompt +++GV$SUBCACHE+++
desc GV$SUBCACHE

prompt +++GV$SUBSCR_REGISTRATION_STATS+++
desc GV$SUBSCR_REGISTRATION_STATS

prompt +++GV$SYSAUX_OCCUPANTS+++
desc GV$SYSAUX_OCCUPANTS

prompt +++GV$SYSMETRIC+++
desc GV$SYSMETRIC

prompt +++GV$SYSMETRIC_HISTORY+++
desc GV$SYSMETRIC_HISTORY

prompt +++GV$SYSMETRIC_SUMMARY+++
desc GV$SYSMETRIC_SUMMARY

prompt +++GV$SYSSTAT+++
desc GV$SYSSTAT

prompt +++GV$SYSTEM_CURSOR_CACHE+++
desc GV$SYSTEM_CURSOR_CACHE

prompt +++GV$SYSTEM_EVENT+++
desc GV$SYSTEM_EVENT

prompt +++GV$SYSTEM_FIX_CONTROL+++
desc GV$SYSTEM_FIX_CONTROL

prompt +++GV$SYSTEM_PARAMETER+++
desc GV$SYSTEM_PARAMETER

prompt +++GV$SYSTEM_PARAMETER2+++
desc GV$SYSTEM_PARAMETER2

prompt +++GV$SYSTEM_PARAMETER3+++
desc GV$SYSTEM_PARAMETER3

prompt +++GV$SYSTEM_PARAMETER4+++
desc GV$SYSTEM_PARAMETER4

prompt +++GV$SYSTEM_WAIT_CLASS+++
desc GV$SYSTEM_WAIT_CLASS

prompt +++GV$SYS_OPTIMIZER_ENV+++
desc GV$SYS_OPTIMIZER_ENV

prompt +++GV$SYS_REPORT_REQUESTS+++
desc GV$SYS_REPORT_REQUESTS

prompt +++GV$SYS_REPORT_STATS+++
desc GV$SYS_REPORT_STATS

prompt +++GV$SYS_TIME_MODEL+++
desc GV$SYS_TIME_MODEL

prompt +++GV$TABLESPACE+++
desc GV$TABLESPACE

prompt +++GV$TEMPFILE+++
desc GV$TEMPFILE

prompt +++GV$TEMPORARY_LOBS+++
desc GV$TEMPORARY_LOBS

prompt +++GV$TEMPSTAT+++
desc GV$TEMPSTAT

prompt +++GV$TEMPUNDOSTAT+++
desc GV$TEMPUNDOSTAT

prompt +++GV$TEMP_CACHE_TRANSFER+++
desc GV$TEMP_CACHE_TRANSFER

prompt +++GV$TEMP_EXTENT_MAP+++
desc GV$TEMP_EXTENT_MAP

prompt +++GV$TEMP_EXTENT_POOL+++
desc GV$TEMP_EXTENT_POOL

prompt +++GV$TEMP_PING+++
desc GV$TEMP_PING

prompt +++GV$TEMP_SPACE_HEADER+++
desc GV$TEMP_SPACE_HEADER

prompt +++GV$THREAD+++
desc GV$THREAD

prompt +++GV$THRESHOLD_TYPES+++
desc GV$THRESHOLD_TYPES

prompt +++GV$TIMER+++
desc GV$TIMER

prompt +++GV$TIMEZONE_FILE+++
desc GV$TIMEZONE_FILE

prompt +++GV$TIMEZONE_NAMES+++
desc GV$TIMEZONE_NAMES

prompt +++GV$TOPLEVELCALL+++
desc GV$TOPLEVELCALL

prompt +++GV$TRANSACTION+++
desc GV$TRANSACTION

prompt +++GV$TRANSACTION_ENQUEUE+++
desc GV$TRANSACTION_ENQUEUE

prompt +++GV$TRANSPORTABLE_PLATFORM+++
desc GV$TRANSPORTABLE_PLATFORM

prompt +++GV$TSDP_SUPPORTED_FEATURE+++
desc GV$TSDP_SUPPORTED_FEATURE

prompt +++GV$TSM_SESSIONS+++
desc GV$TSM_SESSIONS

prompt +++GV$TYPE_SIZE+++
desc GV$TYPE_SIZE

prompt +++GV$UNDOSTAT+++
desc GV$UNDOSTAT

prompt +++GV$UNIFIED_AUDIT_TRAIL+++
desc GV$UNIFIED_AUDIT_TRAIL

prompt +++GV$VERSION+++
desc GV$VERSION

prompt +++GV$VPD_POLICY+++
desc GV$VPD_POLICY

prompt +++GV$WAITCLASSMETRIC+++
desc GV$WAITCLASSMETRIC

prompt +++GV$WAITCLASSMETRIC_HISTORY+++
desc GV$WAITCLASSMETRIC_HISTORY

prompt +++GV$WAITSTAT+++
desc GV$WAITSTAT

prompt +++GV$WALLET+++
desc GV$WALLET

prompt +++GV$WLM_PCMETRIC+++
desc GV$WLM_PCMETRIC

prompt +++GV$WLM_PCMETRIC_HISTORY+++
desc GV$WLM_PCMETRIC_HISTORY

prompt +++GV$WLM_PC_STATS+++
desc GV$WLM_PC_STATS

prompt +++GV$WORKLOAD_REPLAY_THREAD+++
desc GV$WORKLOAD_REPLAY_THREAD

prompt +++GV$XML_AUDIT_TRAIL+++
desc GV$XML_AUDIT_TRAIL

prompt +++GV$XSTREAM_APPLY_COORDINATOR+++
desc GV$XSTREAM_APPLY_COORDINATOR

prompt +++GV$XSTREAM_APPLY_READER+++
desc GV$XSTREAM_APPLY_READER

prompt +++GV$XSTREAM_APPLY_RECEIVER+++
desc GV$XSTREAM_APPLY_RECEIVER

prompt +++GV$XSTREAM_APPLY_SERVER+++
desc GV$XSTREAM_APPLY_SERVER

prompt +++GV$XSTREAM_CAPTURE+++
desc GV$XSTREAM_CAPTURE

prompt +++GV$XSTREAM_MESSAGE_TRACKING+++
desc GV$XSTREAM_MESSAGE_TRACKING

prompt +++GV$XSTREAM_OUTBOUND_SERVER+++
desc GV$XSTREAM_OUTBOUND_SERVER

prompt +++GV$XSTREAM_TABLE_STATS+++
desc GV$XSTREAM_TABLE_STATS

prompt +++GV$XSTREAM_TRANSACTION+++
desc GV$XSTREAM_TRANSACTION

prompt +++GV$XS_SESSIONS+++
desc GV$XS_SESSIONS

prompt +++GV$XS_SESSION_NS_ATTRIBUTE+++
desc GV$XS_SESSION_NS_ATTRIBUTE

prompt +++GV$XS_SESSION_ROLE+++
desc GV$XS_SESSION_ROLE

prompt +++GV$_LOCK+++
desc GV$_LOCK

prompt +++GV$_LOCK1+++
desc GV$_LOCK1

prompt +++GV$_RESUMABLE2+++
desc GV$_RESUMABLE2

prompt +++GV$_SEQUENCES+++
desc GV$_SEQUENCES

prompt +++O$SQL_BIND_CAPTURE+++
desc O$SQL_BIND_CAPTURE

prompt +++V$ACCESS+++
desc V$ACCESS

prompt +++V$ACTIVE_INSTANCES+++
desc V$ACTIVE_INSTANCES

prompt +++V$ACTIVE_SERVICES+++
desc V$ACTIVE_SERVICES

prompt +++V$ACTIVE_SESSION_HISTORY+++
desc V$ACTIVE_SESSION_HISTORY

prompt +++V$ACTIVE_SESS_POOL_MTH+++
desc V$ACTIVE_SESS_POOL_MTH

prompt +++V$ADVISOR_CURRENT_SQLPLAN+++
desc V$ADVISOR_CURRENT_SQLPLAN

prompt +++V$ADVISOR_PROGRESS+++
desc V$ADVISOR_PROGRESS

prompt +++V$ALERT_TYPES+++
desc V$ALERT_TYPES

prompt +++V$AQ1+++
desc V$AQ1

prompt +++V$AQ_BACKGROUND_COORDINATOR+++
desc V$AQ_BACKGROUND_COORDINATOR

prompt +++V$AQ_BMAP_NONDUR_SUBSCRIBERS+++
desc V$AQ_BMAP_NONDUR_SUBSCRIBERS

prompt +++V$AQ_CROSS_INSTANCE_JOBS+++
desc V$AQ_CROSS_INSTANCE_JOBS

prompt +++V$AQ_JOB_COORDINATOR+++
desc V$AQ_JOB_COORDINATOR

prompt +++V$AQ_MESSAGE_CACHE+++
desc V$AQ_MESSAGE_CACHE

prompt +++V$AQ_MSGBM+++
desc V$AQ_MSGBM

prompt +++V$AQ_NONDUR_REGISTRATIONS+++
desc V$AQ_NONDUR_REGISTRATIONS

prompt +++V$AQ_NONDUR_SUBSCRIBER+++
desc V$AQ_NONDUR_SUBSCRIBER

prompt +++V$AQ_NONDUR_SUBSCRIBER_LWM+++
desc V$AQ_NONDUR_SUBSCRIBER_LWM

prompt +++V$AQ_NOTIFICATION_CLIENTS+++
desc V$AQ_NOTIFICATION_CLIENTS

prompt +++V$AQ_SERVER_POOL+++
desc V$AQ_SERVER_POOL

prompt +++V$AQ_SUBSCRIBER_LOAD+++
desc V$AQ_SUBSCRIBER_LOAD

prompt +++V$ARCHIVE+++
desc V$ARCHIVE

prompt +++V$ARCHIVED_LOG+++
desc V$ARCHIVED_LOG

prompt +++V$ARCHIVE_DEST+++
desc V$ARCHIVE_DEST

prompt +++V$ARCHIVE_DEST_STATUS+++
desc V$ARCHIVE_DEST_STATUS

prompt +++V$ARCHIVE_GAP+++
desc V$ARCHIVE_GAP

prompt +++V$ARCHIVE_PROCESSES+++
desc V$ARCHIVE_PROCESSES

prompt +++V$ASH_INFO+++
desc V$ASH_INFO

prompt +++V$ASM_ACFSREPL+++
desc V$ASM_ACFSREPL

prompt +++V$ASM_ACFSREPLTAG+++
desc V$ASM_ACFSREPLTAG

prompt +++V$ASM_ACFSSNAPSHOTS+++
desc V$ASM_ACFSSNAPSHOTS

prompt +++V$ASM_ACFSTAG+++
desc V$ASM_ACFSTAG

prompt +++V$ASM_ACFSVOLUMES+++
desc V$ASM_ACFSVOLUMES

prompt +++V$ASM_ACFS_ENCRYPTION_INFO+++
desc V$ASM_ACFS_ENCRYPTION_INFO

prompt +++V$ASM_ACFS_SECURITY_INFO+++
desc V$ASM_ACFS_SECURITY_INFO

prompt +++V$ASM_ACFS_SEC_ADMIN+++
desc V$ASM_ACFS_SEC_ADMIN

prompt +++V$ASM_ACFS_SEC_CMDRULE+++
desc V$ASM_ACFS_SEC_CMDRULE

prompt +++V$ASM_ACFS_SEC_REALM+++
desc V$ASM_ACFS_SEC_REALM

prompt +++V$ASM_ACFS_SEC_REALM_FILTER+++
desc V$ASM_ACFS_SEC_REALM_FILTER

prompt +++V$ASM_ACFS_SEC_REALM_GROUP+++
desc V$ASM_ACFS_SEC_REALM_GROUP

prompt +++V$ASM_ACFS_SEC_REALM_USER+++
desc V$ASM_ACFS_SEC_REALM_USER

prompt +++V$ASM_ACFS_SEC_RULE+++
desc V$ASM_ACFS_SEC_RULE

prompt +++V$ASM_ACFS_SEC_RULESET+++
desc V$ASM_ACFS_SEC_RULESET

prompt +++V$ASM_ACFS_SEC_RULESET_RULE+++
desc V$ASM_ACFS_SEC_RULESET_RULE

prompt +++V$ASM_ALIAS+++
desc V$ASM_ALIAS

prompt +++V$ASM_ATTRIBUTE+++
desc V$ASM_ATTRIBUTE

prompt +++V$ASM_AUDIT_CLEANUP_JOBS+++
desc V$ASM_AUDIT_CLEANUP_JOBS

prompt +++V$ASM_AUDIT_CLEAN_EVENTS+++
desc V$ASM_AUDIT_CLEAN_EVENTS

prompt +++V$ASM_AUDIT_CONFIG_PARAMS+++
desc V$ASM_AUDIT_CONFIG_PARAMS

prompt +++V$ASM_AUDIT_LAST_ARCH_TS+++
desc V$ASM_AUDIT_LAST_ARCH_TS

prompt +++V$ASM_CLIENT+++
desc V$ASM_CLIENT

prompt +++V$ASM_DISK+++
desc V$ASM_DISK

prompt +++V$ASM_DISKGROUP+++
desc V$ASM_DISKGROUP

prompt +++V$ASM_DISKGROUP_SPARSE+++
desc V$ASM_DISKGROUP_SPARSE

prompt +++V$ASM_DISKGROUP_STAT+++
desc V$ASM_DISKGROUP_STAT

prompt +++V$ASM_DISK_IOSTAT+++
desc V$ASM_DISK_IOSTAT

prompt +++V$ASM_DISK_IOSTAT_SPARSE+++
desc V$ASM_DISK_IOSTAT_SPARSE

prompt +++V$ASM_DISK_SPARSE+++
desc V$ASM_DISK_SPARSE

prompt +++V$ASM_DISK_SPARSE_STAT+++
desc V$ASM_DISK_SPARSE_STAT

prompt +++V$ASM_DISK_STAT+++
desc V$ASM_DISK_STAT

prompt +++V$ASM_ESTIMATE+++
desc V$ASM_ESTIMATE

prompt +++V$ASM_FILE+++
desc V$ASM_FILE

prompt +++V$ASM_FILESYSTEM+++
desc V$ASM_FILESYSTEM

prompt +++V$ASM_OPERATION+++
desc V$ASM_OPERATION

prompt +++V$ASM_TEMPLATE+++
desc V$ASM_TEMPLATE

prompt +++V$ASM_USER+++
desc V$ASM_USER

prompt +++V$ASM_USERGROUP+++
desc V$ASM_USERGROUP

prompt +++V$ASM_USERGROUP_MEMBER+++
desc V$ASM_USERGROUP_MEMBER

prompt +++V$ASM_VOLUME+++
desc V$ASM_VOLUME

prompt +++V$ASM_VOLUME_STAT+++
desc V$ASM_VOLUME_STAT

prompt +++V$AW_AGGREGATE_OP+++
desc V$AW_AGGREGATE_OP

prompt +++V$AW_ALLOCATE_OP+++
desc V$AW_ALLOCATE_OP

prompt +++V$AW_CALC+++
desc V$AW_CALC

prompt +++V$AW_LONGOPS+++
desc V$AW_LONGOPS

prompt +++V$AW_OLAP+++
desc V$AW_OLAP

prompt +++V$AW_SESSION_INFO+++
desc V$AW_SESSION_INFO

prompt +++V$BACKUP+++
desc V$BACKUP

prompt +++V$BACKUP_ARCHIVELOG_DETAILS+++
desc V$BACKUP_ARCHIVELOG_DETAILS

prompt +++V$BACKUP_ARCHIVELOG_SUMMARY+++
desc V$BACKUP_ARCHIVELOG_SUMMARY

prompt +++V$BACKUP_ASYNC_IO+++
desc V$BACKUP_ASYNC_IO

prompt +++V$BACKUP_COMPRESSION_PROGRESS+++
desc V$BACKUP_COMPRESSION_PROGRESS

prompt +++V$BACKUP_CONTROLFILE_DETAILS+++
desc V$BACKUP_CONTROLFILE_DETAILS

prompt +++V$BACKUP_CONTROLFILE_SUMMARY+++
desc V$BACKUP_CONTROLFILE_SUMMARY

prompt +++V$BACKUP_COPY_DETAILS+++
desc V$BACKUP_COPY_DETAILS

prompt +++V$BACKUP_COPY_SUMMARY+++
desc V$BACKUP_COPY_SUMMARY

prompt +++V$BACKUP_CORRUPTION+++
desc V$BACKUP_CORRUPTION

prompt +++V$BACKUP_DATAFILE+++
desc V$BACKUP_DATAFILE

prompt +++V$BACKUP_DATAFILE_DETAILS+++
desc V$BACKUP_DATAFILE_DETAILS

prompt +++V$BACKUP_DATAFILE_SUMMARY+++
desc V$BACKUP_DATAFILE_SUMMARY

prompt +++V$BACKUP_DEVICE+++
desc V$BACKUP_DEVICE

prompt +++V$BACKUP_NONLOGGED+++
desc V$BACKUP_NONLOGGED

prompt +++V$BACKUP_PIECE+++
desc V$BACKUP_PIECE

prompt +++V$BACKUP_PIECE_DETAILS+++
desc V$BACKUP_PIECE_DETAILS

prompt +++V$BACKUP_REDOLOG+++
desc V$BACKUP_REDOLOG

prompt +++V$BACKUP_SET+++
desc V$BACKUP_SET

prompt +++V$BACKUP_SET_DETAILS+++
desc V$BACKUP_SET_DETAILS

prompt +++V$BACKUP_SET_SUMMARY+++
desc V$BACKUP_SET_SUMMARY

prompt +++V$BACKUP_SPFILE+++
desc V$BACKUP_SPFILE

prompt +++V$BACKUP_SPFILE_DETAILS+++
desc V$BACKUP_SPFILE_DETAILS

prompt +++V$BACKUP_SPFILE_SUMMARY+++
desc V$BACKUP_SPFILE_SUMMARY

prompt +++V$BACKUP_SYNC_IO+++
desc V$BACKUP_SYNC_IO

prompt +++V$BGPROCESS+++
desc V$BGPROCESS

prompt +++V$BH+++
desc V$BH

prompt +++V$BLOCKING_QUIESCE+++
desc V$BLOCKING_QUIESCE

prompt +++V$BLOCK_CHANGE_TRACKING+++
desc V$BLOCK_CHANGE_TRACKING

prompt +++V$BSP+++
desc V$BSP

prompt +++V$BTS_STAT+++
desc V$BTS_STAT

prompt +++V$BT_SCAN_CACHE+++
desc V$BT_SCAN_CACHE

prompt +++V$BT_SCAN_OBJ_TEMPS+++
desc V$BT_SCAN_OBJ_TEMPS

prompt +++V$BUFFERED_PUBLISHERS+++
desc V$BUFFERED_PUBLISHERS

prompt +++V$BUFFERED_QUEUES+++
desc V$BUFFERED_QUEUES

prompt +++V$BUFFERED_SUBSCRIBERS+++
desc V$BUFFERED_SUBSCRIBERS

prompt +++V$BUFFER_POOL+++
desc V$BUFFER_POOL

prompt +++V$BUFFER_POOL_STATISTICS+++
desc V$BUFFER_POOL_STATISTICS

prompt +++V$CACHE+++
desc V$CACHE

prompt +++V$CACHE_LOCK+++
desc V$CACHE_LOCK

prompt +++V$CACHE_TRANSFER+++
desc V$CACHE_TRANSFER

prompt +++V$CALLTAG+++
desc V$CALLTAG

prompt +++V$CELL+++
desc V$CELL

prompt +++V$CELL_CONFIG+++
desc V$CELL_CONFIG

prompt +++V$CELL_CONFIG_INFO+++
desc V$CELL_CONFIG_INFO

prompt +++V$CELL_DB+++
desc V$CELL_DB

prompt +++V$CELL_DB_HISTORY+++
desc V$CELL_DB_HISTORY

prompt +++V$CELL_DISK+++
desc V$CELL_DISK

prompt +++V$CELL_DISK_HISTORY+++
desc V$CELL_DISK_HISTORY

prompt +++V$CELL_GLOBAL+++
desc V$CELL_GLOBAL

prompt +++V$CELL_GLOBAL_HISTORY+++
desc V$CELL_GLOBAL_HISTORY

prompt +++V$CELL_IOREASON+++
desc V$CELL_IOREASON

prompt +++V$CELL_IOREASON_NAME+++
desc V$CELL_IOREASON_NAME

prompt +++V$CELL_METRIC_DESC+++
desc V$CELL_METRIC_DESC

prompt +++V$CELL_OFL_THREAD_HISTORY+++
desc V$CELL_OFL_THREAD_HISTORY

prompt +++V$CELL_OPEN_ALERTS+++
desc V$CELL_OPEN_ALERTS

prompt +++V$CELL_REQUEST_TOTALS+++
desc V$CELL_REQUEST_TOTALS

prompt +++V$CELL_STATE+++
desc V$CELL_STATE

prompt +++V$CELL_THREAD_HISTORY+++
desc V$CELL_THREAD_HISTORY

prompt +++V$CHANNEL_WAITS+++
desc V$CHANNEL_WAITS

prompt +++V$CIRCUIT+++
desc V$CIRCUIT

prompt +++V$CLASS_CACHE_TRANSFER+++
desc V$CLASS_CACHE_TRANSFER

prompt +++V$CLASS_PING+++
desc V$CLASS_PING

prompt +++V$CLIENT_RESULT_CACHE_STATS+++
desc V$CLIENT_RESULT_CACHE_STATS

prompt +++V$CLIENT_SECRETS+++
desc V$CLIENT_SECRETS

prompt +++V$CLIENT_STATS+++
desc V$CLIENT_STATS

prompt +++V$CLONEDFILE+++
desc V$CLONEDFILE

prompt +++V$CLUSTER_INTERCONNECTS+++
desc V$CLUSTER_INTERCONNECTS

prompt +++V$CONFIGURED_INTERCONNECTS+++
desc V$CONFIGURED_INTERCONNECTS

prompt +++V$CONTAINERS+++
desc V$CONTAINERS

prompt +++V$CONTEXT+++
desc V$CONTEXT

prompt +++V$CONTROLFILE+++
desc V$CONTROLFILE

prompt +++V$CONTROLFILE_RECORD_SECTION+++
desc V$CONTROLFILE_RECORD_SECTION

prompt +++V$CON_SYSSTAT+++
desc V$CON_SYSSTAT

prompt +++V$CON_SYSTEM_EVENT+++
desc V$CON_SYSTEM_EVENT

prompt +++V$CON_SYSTEM_WAIT_CLASS+++
desc V$CON_SYSTEM_WAIT_CLASS

prompt +++V$CON_SYS_TIME_MODEL+++
desc V$CON_SYS_TIME_MODEL

prompt +++V$COPY_CORRUPTION+++
desc V$COPY_CORRUPTION

prompt +++V$COPY_NONLOGGED+++
desc V$COPY_NONLOGGED

prompt +++V$CORRUPT_XID_LIST+++
desc V$CORRUPT_XID_LIST

prompt +++V$CPOOL_CC_INFO+++
desc V$CPOOL_CC_INFO

prompt +++V$CPOOL_CC_STATS+++
desc V$CPOOL_CC_STATS

prompt +++V$CPOOL_CONN_INFO+++
desc V$CPOOL_CONN_INFO

prompt +++V$CPOOL_STATS+++
desc V$CPOOL_STATS

prompt +++V$CR_BLOCK_SERVER+++
desc V$CR_BLOCK_SERVER

prompt +++V$CURRENT_BLOCK_SERVER+++
desc V$CURRENT_BLOCK_SERVER

prompt +++V$DATABASE+++
desc V$DATABASE

prompt +++V$DATABASE_BLOCK_CORRUPTION+++
desc V$DATABASE_BLOCK_CORRUPTION

prompt +++V$DATABASE_INCARNATION+++
desc V$DATABASE_INCARNATION

prompt +++V$DATABASE_KEY_INFO+++
desc V$DATABASE_KEY_INFO

prompt +++V$DATAFILE+++
desc V$DATAFILE

prompt +++V$DATAFILE_COPY+++
desc V$DATAFILE_COPY

prompt +++V$DATAFILE_HEADER+++
desc V$DATAFILE_HEADER

prompt +++V$DATAGUARD_CONFIG+++
desc V$DATAGUARD_CONFIG

prompt +++V$DATAGUARD_STATS+++
desc V$DATAGUARD_STATS

prompt +++V$DATAGUARD_STATUS+++
desc V$DATAGUARD_STATUS

prompt +++V$DATAPUMP_JOB+++
desc V$DATAPUMP_JOB

prompt +++V$DATAPUMP_SESSION+++
desc V$DATAPUMP_SESSION

prompt +++V$DBFILE+++
desc V$DBFILE

prompt +++V$DBLINK+++
desc V$DBLINK

prompt +++V$DB_CACHE_ADVICE+++
desc V$DB_CACHE_ADVICE

prompt +++V$DB_OBJECT_CACHE+++
desc V$DB_OBJECT_CACHE

prompt +++V$DB_PIPES+++
desc V$DB_PIPES

prompt +++V$DB_TRANSPORTABLE_PLATFORM+++
desc V$DB_TRANSPORTABLE_PLATFORM

prompt +++V$DEAD_CLEANUP+++
desc V$DEAD_CLEANUP

prompt +++V$DELETED_OBJECT+++
desc V$DELETED_OBJECT

prompt +++V$DETACHED_SESSION+++
desc V$DETACHED_SESSION

prompt +++V$DG_BROKER_CONFIG+++
desc V$DG_BROKER_CONFIG

prompt +++V$DIAG_CRITICAL_ERROR+++
desc V$DIAG_CRITICAL_ERROR

prompt +++V$DIAG_INFO+++
desc V$DIAG_INFO

prompt +++V$DISPATCHER+++
desc V$DISPATCHER

prompt +++V$DISPATCHER_CONFIG+++
desc V$DISPATCHER_CONFIG

prompt +++V$DISPATCHER_RATE+++
desc V$DISPATCHER_RATE

prompt +++V$DLM_ALL_LOCKS+++
desc V$DLM_ALL_LOCKS

prompt +++V$DLM_CONVERT_LOCAL+++
desc V$DLM_CONVERT_LOCAL

prompt +++V$DLM_CONVERT_REMOTE+++
desc V$DLM_CONVERT_REMOTE

prompt +++V$DLM_LATCH+++
desc V$DLM_LATCH

prompt +++V$DLM_LOCKS+++
desc V$DLM_LOCKS

prompt +++V$DLM_MISC+++
desc V$DLM_MISC

prompt +++V$DLM_RESS+++
desc V$DLM_RESS

prompt +++V$DLM_TRAFFIC_CONTROLLER+++
desc V$DLM_TRAFFIC_CONTROLLER

prompt +++V$DNFS_CHANNELS+++
desc V$DNFS_CHANNELS

prompt +++V$DNFS_FILES+++
desc V$DNFS_FILES

prompt +++V$DNFS_SERVERS+++
desc V$DNFS_SERVERS

prompt +++V$DNFS_STATS+++
desc V$DNFS_STATS

prompt +++V$DYNAMIC_REMASTER_STATS+++
desc V$DYNAMIC_REMASTER_STATS

prompt +++V$EDITIONABLE_TYPES+++
desc V$EDITIONABLE_TYPES

prompt +++V$EMON+++
desc V$EMON

prompt +++V$EMX_USAGE_STATS+++
desc V$EMX_USAGE_STATS

prompt +++V$ENABLEDPRIVS+++
desc V$ENABLEDPRIVS

prompt +++V$ENCRYPTED_TABLESPACES+++
desc V$ENCRYPTED_TABLESPACES

prompt +++V$ENCRYPTION_KEYS+++
desc V$ENCRYPTION_KEYS

prompt +++V$ENCRYPTION_WALLET+++
desc V$ENCRYPTION_WALLET

prompt +++V$ENQUEUE_LOCK+++
desc V$ENQUEUE_LOCK

prompt +++V$ENQUEUE_STAT+++
desc V$ENQUEUE_STAT

prompt +++V$ENQUEUE_STATISTICS+++
desc V$ENQUEUE_STATISTICS

prompt +++V$EVENTMETRIC+++
desc V$EVENTMETRIC

prompt +++V$EVENT_HISTOGRAM+++
desc V$EVENT_HISTOGRAM

prompt +++V$EVENT_HISTOGRAM_MICRO+++
desc V$EVENT_HISTOGRAM_MICRO

prompt +++V$EVENT_NAME+++
desc V$EVENT_NAME

prompt +++V$EXECUTION+++
desc V$EXECUTION

prompt +++V$FALSE_PING+++
desc V$FALSE_PING

prompt +++V$FAST_START_SERVERS+++
desc V$FAST_START_SERVERS

prompt +++V$FAST_START_TRANSACTIONS+++
desc V$FAST_START_TRANSACTIONS

prompt +++V$FILEMETRIC+++
desc V$FILEMETRIC

prompt +++V$FILEMETRIC_HISTORY+++
desc V$FILEMETRIC_HISTORY

prompt +++V$FILESPACE_USAGE+++
desc V$FILESPACE_USAGE

prompt +++V$FILESTAT+++
desc V$FILESTAT

prompt +++V$FILE_CACHE_TRANSFER+++
desc V$FILE_CACHE_TRANSFER

prompt +++V$FILE_HISTOGRAM+++
desc V$FILE_HISTOGRAM

prompt +++V$FILE_OPTIMIZED_HISTOGRAM+++
desc V$FILE_OPTIMIZED_HISTOGRAM

prompt +++V$FILE_PING+++
desc V$FILE_PING

prompt +++V$FIXED_TABLE+++
desc V$FIXED_TABLE

prompt +++V$FIXED_VIEW_DEFINITION+++
desc V$FIXED_VIEW_DEFINITION

prompt +++V$FLASHBACK_DATABASE_LOG+++
desc V$FLASHBACK_DATABASE_LOG

prompt +++V$FLASHBACK_DATABASE_LOGFILE+++
desc V$FLASHBACK_DATABASE_LOGFILE

prompt +++V$FLASHBACK_DATABASE_STAT+++
desc V$FLASHBACK_DATABASE_STAT

prompt +++V$FLASHBACK_TXN_GRAPH+++
desc V$FLASHBACK_TXN_GRAPH

prompt +++V$FLASHBACK_TXN_MODS+++
desc V$FLASHBACK_TXN_MODS

prompt +++V$FLASHFILESTAT+++
desc V$FLASHFILESTAT

prompt +++V$FLASH_RECOVERY_AREA_USAGE+++
desc V$FLASH_RECOVERY_AREA_USAGE

prompt +++V$FOREIGN_ARCHIVED_LOG+++
desc V$FOREIGN_ARCHIVED_LOG

prompt +++V$FS_FAILOVER_HISTOGRAM+++
desc V$FS_FAILOVER_HISTOGRAM

prompt +++V$FS_FAILOVER_STATS+++
desc V$FS_FAILOVER_STATS

prompt +++V$FS_OBSERVER_HISTOGRAM+++
desc V$FS_OBSERVER_HISTOGRAM

prompt +++V$GCSHVMASTER_INFO+++
desc V$GCSHVMASTER_INFO

prompt +++V$GCSPFMASTER_INFO+++
desc V$GCSPFMASTER_INFO

prompt +++V$GC_ELEMENT+++
desc V$GC_ELEMENT

prompt +++V$GC_ELEMENTS_WITH_COLLISIONS+++
desc V$GC_ELEMENTS_WITH_COLLISIONS

prompt +++V$GES_BLOCKING_ENQUEUE+++
desc V$GES_BLOCKING_ENQUEUE

prompt +++V$GES_DEADLOCKS+++
desc V$GES_DEADLOCKS

prompt +++V$GES_DEADLOCK_SESSIONS+++
desc V$GES_DEADLOCK_SESSIONS

prompt +++V$GES_ENQUEUE+++
desc V$GES_ENQUEUE

prompt +++V$GG_APPLY_COORDINATOR+++
desc V$GG_APPLY_COORDINATOR

prompt +++V$GG_APPLY_READER+++
desc V$GG_APPLY_READER

prompt +++V$GG_APPLY_RECEIVER+++
desc V$GG_APPLY_RECEIVER

prompt +++V$GG_APPLY_SERVER+++
desc V$GG_APPLY_SERVER

prompt +++V$GLOBALCONTEXT+++
desc V$GLOBALCONTEXT

prompt +++V$GLOBAL_BLOCKED_LOCKS+++
desc V$GLOBAL_BLOCKED_LOCKS

prompt +++V$GLOBAL_TRANSACTION+++
desc V$GLOBAL_TRANSACTION

prompt +++V$GOLDENGATE_CAPABILITIES+++
desc V$GOLDENGATE_CAPABILITIES

prompt +++V$GOLDENGATE_CAPTURE+++
desc V$GOLDENGATE_CAPTURE

prompt +++V$GOLDENGATE_MESSAGE_TRACKING+++
desc V$GOLDENGATE_MESSAGE_TRACKING

prompt +++V$GOLDENGATE_TABLE_STATS+++
desc V$GOLDENGATE_TABLE_STATS

prompt +++V$GOLDENGATE_TRANSACTION+++
desc V$GOLDENGATE_TRANSACTION

prompt +++V$HANG_INFO+++
desc V$HANG_INFO

prompt +++V$HANG_SESSION_INFO+++
desc V$HANG_SESSION_INFO

prompt +++V$HANG_STATISTICS+++
desc V$HANG_STATISTICS

prompt +++V$HEAT_MAP_SEGMENT+++
desc V$HEAT_MAP_SEGMENT

prompt +++V$HM_CHECK+++
desc V$HM_CHECK

prompt +++V$HM_CHECK_PARAM+++
desc V$HM_CHECK_PARAM

prompt +++V$HM_FINDING+++
desc V$HM_FINDING

prompt +++V$HM_INFO+++
desc V$HM_INFO

prompt +++V$HM_RECOMMENDATION+++
desc V$HM_RECOMMENDATION

prompt +++V$HM_RUN+++
desc V$HM_RUN

prompt +++V$HS_AGENT+++
desc V$HS_AGENT

prompt +++V$HS_PARAMETER+++
desc V$HS_PARAMETER

prompt +++V$HS_SESSION+++
desc V$HS_SESSION

prompt +++V$HVMASTER_INFO+++
desc V$HVMASTER_INFO

prompt +++V$IM_COLUMN_LEVEL+++
desc V$IM_COLUMN_LEVEL

prompt +++V$IM_COL_CU+++
desc V$IM_COL_CU

prompt +++V$IM_HEADER+++
desc V$IM_HEADER

prompt +++V$IM_SEGMENTS+++
desc V$IM_SEGMENTS

prompt +++V$IM_SEGMENTS_DETAIL+++
desc V$IM_SEGMENTS_DETAIL

prompt +++V$IM_SEG_EXT_MAP+++
desc V$IM_SEG_EXT_MAP

prompt +++V$IM_SMU_CHUNK+++
desc V$IM_SMU_CHUNK

prompt +++V$IM_SMU_HEAD+++
desc V$IM_SMU_HEAD

prompt +++V$IM_TBS_EXT_MAP+++
desc V$IM_TBS_EXT_MAP

prompt +++V$IM_USER_SEGMENTS+++
desc V$IM_USER_SEGMENTS

prompt +++V$INCMETER_CONFIG+++
desc V$INCMETER_CONFIG

prompt +++V$INCMETER_INFO+++
desc V$INCMETER_INFO

prompt +++V$INCMETER_SUMMARY+++
desc V$INCMETER_SUMMARY

prompt +++V$INDEXED_FIXED_COLUMN+++
desc V$INDEXED_FIXED_COLUMN

prompt +++V$INMEMORY_AREA+++
desc V$INMEMORY_AREA

prompt +++V$INSTANCE+++
desc V$INSTANCE

prompt +++V$INSTANCE_CACHE_TRANSFER+++
desc V$INSTANCE_CACHE_TRANSFER

prompt +++V$INSTANCE_LOG_GROUP+++
desc V$INSTANCE_LOG_GROUP

prompt +++V$INSTANCE_PING+++
desc V$INSTANCE_PING

prompt +++V$INSTANCE_RECOVERY+++
desc V$INSTANCE_RECOVERY

prompt +++V$IOFUNCMETRIC+++
desc V$IOFUNCMETRIC

prompt +++V$IOFUNCMETRIC_HISTORY+++
desc V$IOFUNCMETRIC_HISTORY

prompt +++V$IOSTAT_CONSUMER_GROUP+++
desc V$IOSTAT_CONSUMER_GROUP

prompt +++V$IOSTAT_FILE+++
desc V$IOSTAT_FILE

prompt +++V$IOSTAT_FUNCTION+++
desc V$IOSTAT_FUNCTION

prompt +++V$IOSTAT_FUNCTION_DETAIL+++
desc V$IOSTAT_FUNCTION_DETAIL

prompt +++V$IOSTAT_NETWORK+++
desc V$IOSTAT_NETWORK

prompt +++V$IOS_CLIENT+++
desc V$IOS_CLIENT

prompt +++V$IO_CALIBRATION_STATUS+++
desc V$IO_CALIBRATION_STATUS

prompt +++V$IO_OUTLIER+++
desc V$IO_OUTLIER

prompt +++V$IR_FAILURE+++
desc V$IR_FAILURE

prompt +++V$IR_FAILURE_SET+++
desc V$IR_FAILURE_SET

prompt +++V$IR_MANUAL_CHECKLIST+++
desc V$IR_MANUAL_CHECKLIST

prompt +++V$IR_REPAIR+++
desc V$IR_REPAIR

prompt +++V$JAVAPOOL+++
desc V$JAVAPOOL

prompt +++V$JAVA_LIBRARY_CACHE_MEMORY+++
desc V$JAVA_LIBRARY_CACHE_MEMORY

prompt +++V$JAVA_POOL_ADVICE+++
desc V$JAVA_POOL_ADVICE

prompt +++V$KERNEL_IO_OUTLIER+++
desc V$KERNEL_IO_OUTLIER

prompt +++V$KEY_VECTOR+++
desc V$KEY_VECTOR

prompt +++V$LATCH+++
desc V$LATCH

prompt +++V$LATCHHOLDER+++
desc V$LATCHHOLDER

prompt +++V$LATCHNAME+++
desc V$LATCHNAME

prompt +++V$LATCH_CHILDREN+++
desc V$LATCH_CHILDREN

prompt +++V$LATCH_MISSES+++
desc V$LATCH_MISSES

prompt +++V$LATCH_PARENT+++
desc V$LATCH_PARENT

prompt +++V$LGWRIO_OUTLIER+++
desc V$LGWRIO_OUTLIER

prompt +++V$LIBCACHE_LOCKS+++
desc V$LIBCACHE_LOCKS

prompt +++V$LIBRARYCACHE+++
desc V$LIBRARYCACHE

prompt +++V$LIBRARY_CACHE_MEMORY+++
desc V$LIBRARY_CACHE_MEMORY

prompt +++V$LICENSE+++
desc V$LICENSE

prompt +++V$LISTENER_NETWORK+++
desc V$LISTENER_NETWORK

prompt +++V$LOADISTAT+++
desc V$LOADISTAT

prompt +++V$LOADPSTAT+++
desc V$LOADPSTAT

prompt +++V$LOBSTAT+++
desc V$LOBSTAT

prompt +++V$LOCK+++
desc V$LOCK

prompt +++V$LOCKED_OBJECT+++
desc V$LOCKED_OBJECT

prompt +++V$LOCKS_WITH_COLLISIONS+++
desc V$LOCKS_WITH_COLLISIONS

prompt +++V$LOCK_ACTIVITY+++
desc V$LOCK_ACTIVITY

prompt +++V$LOCK_ELEMENT+++
desc V$LOCK_ELEMENT

prompt +++V$LOCK_TYPE+++
desc V$LOCK_TYPE

prompt +++V$LOG+++
desc V$LOG

prompt +++V$LOGFILE+++
desc V$LOGFILE

prompt +++V$LOGHIST+++
desc V$LOGHIST

prompt +++V$LOGMNR_CONTENTS+++
desc V$LOGMNR_CONTENTS

prompt +++V$LOGMNR_DBA_OBJECTS+++
desc V$LOGMNR_DBA_OBJECTS

prompt +++V$LOGMNR_DICTIONARY+++
desc V$LOGMNR_DICTIONARY

prompt +++V$LOGMNR_DICTIONARY_LOAD+++
desc V$LOGMNR_DICTIONARY_LOAD

prompt +++V$LOGMNR_EXTENTS+++
desc V$LOGMNR_EXTENTS

prompt +++V$LOGMNR_LATCH+++
desc V$LOGMNR_LATCH

prompt +++V$LOGMNR_LOGFILE+++
desc V$LOGMNR_LOGFILE

prompt +++V$LOGMNR_LOGS+++
desc V$LOGMNR_LOGS

prompt +++V$LOGMNR_OBJECT_SEGMENTS+++
desc V$LOGMNR_OBJECT_SEGMENTS

prompt +++V$LOGMNR_PARAMETERS+++
desc V$LOGMNR_PARAMETERS

prompt +++V$LOGMNR_PROCESS+++
desc V$LOGMNR_PROCESS

prompt +++V$LOGMNR_SESSION+++
desc V$LOGMNR_SESSION

prompt +++V$LOGMNR_STATS+++
desc V$LOGMNR_STATS

prompt +++V$LOGMNR_SYS_DBA_SEGS+++
desc V$LOGMNR_SYS_DBA_SEGS

prompt +++V$LOGMNR_SYS_OBJECTS+++
desc V$LOGMNR_SYS_OBJECTS

prompt +++V$LOGMNR_TRANSACTION+++
desc V$LOGMNR_TRANSACTION

prompt +++V$LOGSTDBY+++
desc V$LOGSTDBY

prompt +++V$LOGSTDBY_PROCESS+++
desc V$LOGSTDBY_PROCESS

prompt +++V$LOGSTDBY_PROGRESS+++
desc V$LOGSTDBY_PROGRESS

prompt +++V$LOGSTDBY_STATE+++
desc V$LOGSTDBY_STATE

prompt +++V$LOGSTDBY_STATS+++
desc V$LOGSTDBY_STATS

prompt +++V$LOGSTDBY_TRANSACTION+++
desc V$LOGSTDBY_TRANSACTION

prompt +++V$LOG_HISTORY+++
desc V$LOG_HISTORY

prompt +++V$MANAGED_STANDBY+++
desc V$MANAGED_STANDBY

prompt +++V$MAPPED_SQL+++
desc V$MAPPED_SQL

prompt +++V$MAP_COMP_LIST+++
desc V$MAP_COMP_LIST

prompt +++V$MAP_ELEMENT+++
desc V$MAP_ELEMENT

prompt +++V$MAP_EXT_ELEMENT+++
desc V$MAP_EXT_ELEMENT

prompt +++V$MAP_FILE+++
desc V$MAP_FILE

prompt +++V$MAP_FILE_EXTENT+++
desc V$MAP_FILE_EXTENT

prompt +++V$MAP_FILE_IO_STACK+++
desc V$MAP_FILE_IO_STACK

prompt +++V$MAP_LIBRARY+++
desc V$MAP_LIBRARY

prompt +++V$MAP_SUBELEMENT+++
desc V$MAP_SUBELEMENT

prompt +++V$MAX_ACTIVE_SESS_TARGET_MTH+++
desc V$MAX_ACTIVE_SESS_TARGET_MTH

prompt +++V$MEMORY_CURRENT_RESIZE_OPS+++
desc V$MEMORY_CURRENT_RESIZE_OPS

prompt +++V$MEMORY_DYNAMIC_COMPONENTS+++
desc V$MEMORY_DYNAMIC_COMPONENTS

prompt +++V$MEMORY_RESIZE_OPS+++
desc V$MEMORY_RESIZE_OPS

prompt +++V$MEMORY_TARGET_ADVICE+++
desc V$MEMORY_TARGET_ADVICE

prompt +++V$METRIC+++
desc V$METRIC

prompt +++V$METRICGROUP+++
desc V$METRICGROUP

prompt +++V$METRICNAME+++
desc V$METRICNAME

prompt +++V$METRIC_HISTORY+++
desc V$METRIC_HISTORY

prompt +++V$MTTR_TARGET_ADVICE+++
desc V$MTTR_TARGET_ADVICE

prompt +++V$MUTEX_SLEEP+++
desc V$MUTEX_SLEEP

prompt +++V$MUTEX_SLEEP_HISTORY+++
desc V$MUTEX_SLEEP_HISTORY

prompt +++V$MVREFRESH+++
desc V$MVREFRESH

prompt +++V$MYSTAT+++
desc V$MYSTAT

prompt +++V$NFS_CLIENTS+++
desc V$NFS_CLIENTS

prompt +++V$NFS_LOCKS+++
desc V$NFS_LOCKS

prompt +++V$NFS_OPEN_FILES+++
desc V$NFS_OPEN_FILES

prompt +++V$NLS_PARAMETERS+++
desc V$NLS_PARAMETERS

prompt +++V$NLS_VALID_VALUES+++
desc V$NLS_VALID_VALUES

prompt +++V$NONLOGGED_BLOCK+++
desc V$NONLOGGED_BLOCK

prompt +++V$OBJECT_DEPENDENCY+++
desc V$OBJECT_DEPENDENCY

prompt +++V$OBJECT_DML_FREQUENCIES+++
desc V$OBJECT_DML_FREQUENCIES

prompt +++V$OBJECT_PRIVILEGE+++
desc V$OBJECT_PRIVILEGE

prompt +++V$OBSOLETE_PARAMETER+++
desc V$OBSOLETE_PARAMETER

prompt +++V$OFFLINE_RANGE+++
desc V$OFFLINE_RANGE

prompt +++V$OFSMOUNT+++
desc V$OFSMOUNT

prompt +++V$OFS_STATS+++
desc V$OFS_STATS

prompt +++V$OPEN_CURSOR+++
desc V$OPEN_CURSOR

prompt +++V$OPTIMIZER_PROCESSING_RATE+++
desc V$OPTIMIZER_PROCESSING_RATE

prompt +++V$OPTION+++
desc V$OPTION

prompt +++V$OSSTAT+++
desc V$OSSTAT

prompt +++V$PARALLEL_DEGREE_LIMIT_MTH+++
desc V$PARALLEL_DEGREE_LIMIT_MTH

prompt +++V$PARAMETER+++
desc V$PARAMETER

prompt +++V$PARAMETER2+++
desc V$PARAMETER2

prompt +++V$PARAMETER_VALID_VALUES+++
desc V$PARAMETER_VALID_VALUES

prompt +++V$PATCHES+++
desc V$PATCHES

prompt +++V$PDBS+++
desc V$PDBS

prompt +++V$PDB_INCARNATION+++
desc V$PDB_INCARNATION

prompt +++V$PERSISTENT_PUBLISHERS+++
desc V$PERSISTENT_PUBLISHERS

prompt +++V$PERSISTENT_QMN_CACHE+++
desc V$PERSISTENT_QMN_CACHE

prompt +++V$PERSISTENT_QUEUES+++
desc V$PERSISTENT_QUEUES

prompt +++V$PERSISTENT_SUBSCRIBERS+++
desc V$PERSISTENT_SUBSCRIBERS

prompt +++V$PGASTAT+++
desc V$PGASTAT

prompt +++V$PGA_TARGET_ADVICE+++
desc V$PGA_TARGET_ADVICE

prompt +++V$PGA_TARGET_ADVICE_HISTOGRAM+++
desc V$PGA_TARGET_ADVICE_HISTOGRAM

prompt +++V$PING+++
desc V$PING

prompt +++V$POLICY_HISTORY+++
desc V$POLICY_HISTORY

prompt +++V$PQ_SESSTAT+++
desc V$PQ_SESSTAT

prompt +++V$PQ_SLAVE+++
desc V$PQ_SLAVE

prompt +++V$PQ_SYSSTAT+++
desc V$PQ_SYSSTAT

prompt +++V$PQ_TQSTAT+++
desc V$PQ_TQSTAT

prompt +++V$PROCESS+++
desc V$PROCESS

prompt +++V$PROCESS_GROUP+++
desc V$PROCESS_GROUP

prompt +++V$PROCESS_MEMORY+++
desc V$PROCESS_MEMORY

prompt +++V$PROCESS_MEMORY_DETAIL+++
desc V$PROCESS_MEMORY_DETAIL

prompt +++V$PROCESS_MEMORY_DETAIL_PROG+++
desc V$PROCESS_MEMORY_DETAIL_PROG

prompt +++V$PROPAGATION_RECEIVER+++
desc V$PROPAGATION_RECEIVER

prompt +++V$PROPAGATION_SENDER+++
desc V$PROPAGATION_SENDER

prompt +++V$PROXY_ARCHIVEDLOG+++
desc V$PROXY_ARCHIVEDLOG

prompt +++V$PROXY_ARCHIVELOG_DETAILS+++
desc V$PROXY_ARCHIVELOG_DETAILS

prompt +++V$PROXY_ARCHIVELOG_SUMMARY+++
desc V$PROXY_ARCHIVELOG_SUMMARY

prompt +++V$PROXY_COPY_DETAILS+++
desc V$PROXY_COPY_DETAILS

prompt +++V$PROXY_COPY_SUMMARY+++
desc V$PROXY_COPY_SUMMARY

prompt +++V$PROXY_DATAFILE+++
desc V$PROXY_DATAFILE

prompt +++V$PWFILE_USERS+++
desc V$PWFILE_USERS

prompt +++V$PX_BUFFER_ADVICE+++
desc V$PX_BUFFER_ADVICE

prompt +++V$PX_INSTANCE_GROUP+++
desc V$PX_INSTANCE_GROUP

prompt +++V$PX_PROCESS+++
desc V$PX_PROCESS

prompt +++V$PX_PROCESS_SYSSTAT+++
desc V$PX_PROCESS_SYSSTAT

prompt +++V$PX_PROCESS_TRACE+++
desc V$PX_PROCESS_TRACE

prompt +++V$PX_SESSION+++
desc V$PX_SESSION

prompt +++V$PX_SESSTAT+++
desc V$PX_SESSTAT

prompt +++V$QMON_COORDINATOR_STATS+++
desc V$QMON_COORDINATOR_STATS

prompt +++V$QMON_SERVER_STATS+++
desc V$QMON_SERVER_STATS

prompt +++V$QMON_TASKS+++
desc V$QMON_TASKS

prompt +++V$QMON_TASK_STATS+++
desc V$QMON_TASK_STATS

prompt +++V$QPX_INVENTORY+++
desc V$QPX_INVENTORY

prompt +++V$QUEUE+++
desc V$QUEUE

prompt +++V$QUEUEING_MTH+++
desc V$QUEUEING_MTH

prompt +++V$RECOVERY_AREA_USAGE+++
desc V$RECOVERY_AREA_USAGE

prompt +++V$RECOVERY_FILE_DEST+++
desc V$RECOVERY_FILE_DEST

prompt +++V$RECOVERY_FILE_STATUS+++
desc V$RECOVERY_FILE_STATUS

prompt +++V$RECOVERY_LOG+++
desc V$RECOVERY_LOG

prompt +++V$RECOVERY_PROGRESS+++
desc V$RECOVERY_PROGRESS

prompt +++V$RECOVERY_STATUS+++
desc V$RECOVERY_STATUS

prompt +++V$RECOVER_FILE+++
desc V$RECOVER_FILE

prompt +++V$REDO_DEST_RESP_HISTOGRAM+++
desc V$REDO_DEST_RESP_HISTOGRAM

prompt +++V$REPLAY_CONTEXT+++
desc V$REPLAY_CONTEXT

prompt +++V$REPLAY_CONTEXT_LOB+++
desc V$REPLAY_CONTEXT_LOB

prompt +++V$REPLAY_CONTEXT_SEQUENCE+++
desc V$REPLAY_CONTEXT_SEQUENCE

prompt +++V$REPLAY_CONTEXT_SYSDATE+++
desc V$REPLAY_CONTEXT_SYSDATE

prompt +++V$REPLAY_CONTEXT_SYSGUID+++
desc V$REPLAY_CONTEXT_SYSGUID

prompt +++V$REPLAY_CONTEXT_SYSTIMESTAMP+++
desc V$REPLAY_CONTEXT_SYSTIMESTAMP

prompt +++V$REPLPROP+++
desc V$REPLPROP

prompt +++V$REPLQUEUE+++
desc V$REPLQUEUE

prompt +++V$REQDIST+++
desc V$REQDIST

prompt +++V$RESERVED_WORDS+++
desc V$RESERVED_WORDS

prompt +++V$RESOURCE+++
desc V$RESOURCE

prompt +++V$RESOURCE_LIMIT+++
desc V$RESOURCE_LIMIT

prompt +++V$RESTORE_POINT+++
desc V$RESTORE_POINT

prompt +++V$RESULT_CACHE_DEPENDENCY+++
desc V$RESULT_CACHE_DEPENDENCY

prompt +++V$RESULT_CACHE_DR+++
desc V$RESULT_CACHE_DR

prompt +++V$RESULT_CACHE_MEMORY+++
desc V$RESULT_CACHE_MEMORY

prompt +++V$RESULT_CACHE_OBJECTS+++
desc V$RESULT_CACHE_OBJECTS

prompt +++V$RESULT_CACHE_RD+++
desc V$RESULT_CACHE_RD

prompt +++V$RESULT_CACHE_RR+++
desc V$RESULT_CACHE_RR

prompt +++V$RESULT_CACHE_STATISTICS+++
desc V$RESULT_CACHE_STATISTICS

prompt +++V$RESUMABLE+++
desc V$RESUMABLE

prompt +++V$RFS_THREAD+++
desc V$RFS_THREAD

prompt +++V$RMAN_BACKUP_JOB_DETAILS+++
desc V$RMAN_BACKUP_JOB_DETAILS

prompt +++V$RMAN_BACKUP_SUBJOB_DETAILS+++
desc V$RMAN_BACKUP_SUBJOB_DETAILS

prompt +++V$RMAN_BACKUP_TYPE+++
desc V$RMAN_BACKUP_TYPE

prompt +++V$RMAN_COMPRESSION_ALGORITHM+++
desc V$RMAN_COMPRESSION_ALGORITHM

prompt +++V$RMAN_CONFIGURATION+++
desc V$RMAN_CONFIGURATION

prompt +++V$RMAN_ENCRYPTION_ALGORITHMS+++
desc V$RMAN_ENCRYPTION_ALGORITHMS

prompt +++V$RMAN_OUTPUT+++
desc V$RMAN_OUTPUT

prompt +++V$RMAN_STATUS+++
desc V$RMAN_STATUS

prompt +++V$ROLLSTAT+++
desc V$ROLLSTAT

prompt +++V$ROWCACHE+++
desc V$ROWCACHE

prompt +++V$ROWCACHE_PARENT+++
desc V$ROWCACHE_PARENT

prompt +++V$ROWCACHE_SUBORDINATE+++
desc V$ROWCACHE_SUBORDINATE

prompt +++V$RO_USER_ACCOUNT+++
desc V$RO_USER_ACCOUNT

prompt +++V$RSRCMGRMETRIC+++
desc V$RSRCMGRMETRIC

prompt +++V$RSRCMGRMETRIC_HISTORY+++
desc V$RSRCMGRMETRIC_HISTORY

prompt +++V$RSRC_CONSUMER_GROUP+++
desc V$RSRC_CONSUMER_GROUP

prompt +++V$RSRC_CONSUMER_GROUP_CPU_MTH+++
desc V$RSRC_CONSUMER_GROUP_CPU_MTH

prompt +++V$RSRC_CONS_GROUP_HISTORY+++
desc V$RSRC_CONS_GROUP_HISTORY

prompt +++V$RSRC_PLAN+++
desc V$RSRC_PLAN

prompt +++V$RSRC_PLAN_CPU_MTH+++
desc V$RSRC_PLAN_CPU_MTH

prompt +++V$RSRC_PLAN_HISTORY+++
desc V$RSRC_PLAN_HISTORY

prompt +++V$RSRC_SESSION_INFO+++
desc V$RSRC_SESSION_INFO

prompt +++V$RT_ADDM_CONTROL+++
desc V$RT_ADDM_CONTROL

prompt +++V$RULE+++
desc V$RULE

prompt +++V$RULE_SET+++
desc V$RULE_SET

prompt +++V$RULE_SET_AGGREGATE_STATS+++
desc V$RULE_SET_AGGREGATE_STATS

prompt +++V$SCHEDULER_INMEM_MDINFO+++
desc V$SCHEDULER_INMEM_MDINFO

prompt +++V$SCHEDULER_INMEM_RTINFO+++
desc V$SCHEDULER_INMEM_RTINFO

prompt +++V$SCHEDULER_RUNNING_JOBS+++
desc V$SCHEDULER_RUNNING_JOBS

prompt +++V$SECUREFILE_TIMER+++
desc V$SECUREFILE_TIMER

prompt +++V$SEGMENT_STATISTICS+++
desc V$SEGMENT_STATISTICS

prompt +++V$SEGSPACE_USAGE+++
desc V$SEGSPACE_USAGE

prompt +++V$SEGSTAT+++
desc V$SEGSTAT

prompt +++V$SEGSTAT_NAME+++
desc V$SEGSTAT_NAME

prompt +++V$SERVICEMETRIC+++
desc V$SERVICEMETRIC

prompt +++V$SERVICEMETRIC_HISTORY+++
desc V$SERVICEMETRIC_HISTORY

prompt +++V$SERVICES+++
desc V$SERVICES

prompt +++V$SERVICE_EVENT+++
desc V$SERVICE_EVENT

prompt +++V$SERVICE_STATS+++
desc V$SERVICE_STATS

prompt +++V$SERVICE_WAIT_CLASS+++
desc V$SERVICE_WAIT_CLASS

prompt +++V$SERV_MOD_ACT_STATS+++
desc V$SERV_MOD_ACT_STATS

prompt +++V$SESSION+++
desc V$SESSION

prompt +++V$SESSIONS_COUNT+++
desc V$SESSIONS_COUNT

prompt +++V$SESSION_BLOCKERS+++
desc V$SESSION_BLOCKERS

prompt +++V$SESSION_CLIENT_RESULT_CACHE+++
desc V$SESSION_CLIENT_RESULT_CACHE

prompt +++V$SESSION_CONNECT_INFO+++
desc V$SESSION_CONNECT_INFO

prompt +++V$SESSION_CURSOR_CACHE+++
desc V$SESSION_CURSOR_CACHE

prompt +++V$SESSION_EVENT+++
desc V$SESSION_EVENT

prompt +++V$SESSION_FIX_CONTROL+++
desc V$SESSION_FIX_CONTROL

prompt +++V$SESSION_LONGOPS+++
desc V$SESSION_LONGOPS

prompt +++V$SESSION_OBJECT_CACHE+++
desc V$SESSION_OBJECT_CACHE

prompt +++V$SESSION_WAIT+++
desc V$SESSION_WAIT

prompt +++V$SESSION_WAIT_CLASS+++
desc V$SESSION_WAIT_CLASS

prompt +++V$SESSION_WAIT_HISTORY+++
desc V$SESSION_WAIT_HISTORY

prompt +++V$SESSMETRIC+++
desc V$SESSMETRIC

prompt +++V$SESSTAT+++
desc V$SESSTAT

prompt +++V$SESS_IO+++
desc V$SESS_IO

prompt +++V$SESS_TIME_MODEL+++
desc V$SESS_TIME_MODEL

prompt +++V$SES_OPTIMIZER_ENV+++
desc V$SES_OPTIMIZER_ENV

prompt +++V$SGA+++
desc V$SGA

prompt +++V$SGAINFO+++
desc V$SGAINFO

prompt +++V$SGASTAT+++
desc V$SGASTAT

prompt +++V$SGA_CURRENT_RESIZE_OPS+++
desc V$SGA_CURRENT_RESIZE_OPS

prompt +++V$SGA_DYNAMIC_COMPONENTS+++
desc V$SGA_DYNAMIC_COMPONENTS

prompt +++V$SGA_DYNAMIC_FREE_MEMORY+++
desc V$SGA_DYNAMIC_FREE_MEMORY

prompt +++V$SGA_RESIZE_OPS+++
desc V$SGA_RESIZE_OPS

prompt +++V$SGA_TARGET_ADVICE+++
desc V$SGA_TARGET_ADVICE

prompt +++V$SHARED_POOL_ADVICE+++
desc V$SHARED_POOL_ADVICE

prompt +++V$SHARED_POOL_RESERVED+++
desc V$SHARED_POOL_RESERVED

prompt +++V$SHARED_SERVER+++
desc V$SHARED_SERVER

prompt +++V$SHARED_SERVER_MONITOR+++
desc V$SHARED_SERVER_MONITOR

prompt +++V$SORT_SEGMENT+++
desc V$SORT_SEGMENT

prompt +++V$SORT_USAGE+++
desc V$SORT_USAGE

prompt +++V$SPPARAMETER+++
desc V$SPPARAMETER

prompt +++V$SQL+++
desc V$SQL

prompt +++V$SQLAREA+++
desc V$SQLAREA

prompt +++V$SQLAREA_PLAN_HASH+++
desc V$SQLAREA_PLAN_HASH

prompt +++V$SQLCOMMAND+++
desc V$SQLCOMMAND

prompt +++V$SQLFN_ARG_METADATA+++
desc V$SQLFN_ARG_METADATA

prompt +++V$SQLFN_METADATA+++
desc V$SQLFN_METADATA

prompt +++V$SQLPA_METRIC+++
desc V$SQLPA_METRIC

prompt +++V$SQLSTATS+++
desc V$SQLSTATS

prompt +++V$SQLSTATS_PLAN_HASH+++
desc V$SQLSTATS_PLAN_HASH

prompt +++V$SQLTEXT+++
desc V$SQLTEXT

prompt +++V$SQLTEXT_WITH_NEWLINES+++
desc V$SQLTEXT_WITH_NEWLINES

prompt +++V$SQL_BIND_DATA+++
desc V$SQL_BIND_DATA

prompt +++V$SQL_BIND_METADATA+++
desc V$SQL_BIND_METADATA

prompt +++V$SQL_CS_HISTOGRAM+++
desc V$SQL_CS_HISTOGRAM

prompt +++V$SQL_CS_SELECTIVITY+++
desc V$SQL_CS_SELECTIVITY

prompt +++V$SQL_CS_STATISTICS+++
desc V$SQL_CS_STATISTICS

prompt +++V$SQL_CURSOR+++
desc V$SQL_CURSOR

prompt +++V$SQL_DIAG_REPOSITORY+++
desc V$SQL_DIAG_REPOSITORY

prompt +++V$SQL_DIAG_REPOSITORY_REASON+++
desc V$SQL_DIAG_REPOSITORY_REASON

prompt +++V$SQL_FEATURE+++
desc V$SQL_FEATURE

prompt +++V$SQL_FEATURE_DEPENDENCY+++
desc V$SQL_FEATURE_DEPENDENCY

prompt +++V$SQL_FEATURE_HIERARCHY+++
desc V$SQL_FEATURE_HIERARCHY

prompt +++V$SQL_HINT+++
desc V$SQL_HINT

prompt +++V$SQL_JOIN_FILTER+++
desc V$SQL_JOIN_FILTER

prompt +++V$SQL_MONITOR+++
desc V$SQL_MONITOR

prompt +++V$SQL_MONITOR_SESSTAT+++
desc V$SQL_MONITOR_SESSTAT

prompt +++V$SQL_MONITOR_STATNAME+++
desc V$SQL_MONITOR_STATNAME

prompt +++V$SQL_OPTIMIZER_ENV+++
desc V$SQL_OPTIMIZER_ENV

prompt +++V$SQL_PLAN+++
desc V$SQL_PLAN

prompt +++V$SQL_PLAN_MONITOR+++
desc V$SQL_PLAN_MONITOR

prompt +++V$SQL_PLAN_STATISTICS+++
desc V$SQL_PLAN_STATISTICS

prompt +++V$SQL_PLAN_STATISTICS_ALL+++
desc V$SQL_PLAN_STATISTICS_ALL

prompt +++V$SQL_REDIRECTION+++
desc V$SQL_REDIRECTION

prompt +++V$SQL_REOPTIMIZATION_HINTS+++
desc V$SQL_REOPTIMIZATION_HINTS

prompt +++V$SQL_SHARED_CURSOR+++
desc V$SQL_SHARED_CURSOR

prompt +++V$SQL_SHARED_MEMORY+++
desc V$SQL_SHARED_MEMORY

prompt +++V$SQL_WORKAREA+++
desc V$SQL_WORKAREA

prompt +++V$SQL_WORKAREA_ACTIVE+++
desc V$SQL_WORKAREA_ACTIVE

prompt +++V$SQL_WORKAREA_HISTOGRAM+++
desc V$SQL_WORKAREA_HISTOGRAM

prompt +++V$SSCR_SESSIONS+++
desc V$SSCR_SESSIONS

prompt +++V$STANDBY_EVENT_HISTOGRAM+++
desc V$STANDBY_EVENT_HISTOGRAM

prompt +++V$STANDBY_LOG+++
desc V$STANDBY_LOG

prompt +++V$STATISTICS_LEVEL+++
desc V$STATISTICS_LEVEL

prompt +++V$STATNAME+++
desc V$STATNAME

prompt +++V$STREAMS_APPLY_COORDINATOR+++
desc V$STREAMS_APPLY_COORDINATOR

prompt +++V$STREAMS_APPLY_READER+++
desc V$STREAMS_APPLY_READER

prompt +++V$STREAMS_APPLY_SERVER+++
desc V$STREAMS_APPLY_SERVER

prompt +++V$STREAMS_CAPTURE+++
desc V$STREAMS_CAPTURE

prompt +++V$STREAMS_MESSAGE_TRACKING+++
desc V$STREAMS_MESSAGE_TRACKING

prompt +++V$STREAMS_POOL_ADVICE+++
desc V$STREAMS_POOL_ADVICE

prompt +++V$STREAMS_POOL_STATISTICS+++
desc V$STREAMS_POOL_STATISTICS

prompt +++V$STREAMS_TRANSACTION+++
desc V$STREAMS_TRANSACTION

prompt +++V$SUBCACHE+++
desc V$SUBCACHE

prompt +++V$SUBSCR_REGISTRATION_STATS+++
desc V$SUBSCR_REGISTRATION_STATS

prompt +++V$SYSAUX_OCCUPANTS+++
desc V$SYSAUX_OCCUPANTS

prompt +++V$SYSMETRIC+++
desc V$SYSMETRIC

prompt +++V$SYSMETRIC_HISTORY+++
desc V$SYSMETRIC_HISTORY

prompt +++V$SYSMETRIC_SUMMARY+++
desc V$SYSMETRIC_SUMMARY

prompt +++V$SYSSTAT+++
desc V$SYSSTAT

prompt +++V$SYSTEM_CURSOR_CACHE+++
desc V$SYSTEM_CURSOR_CACHE

prompt +++V$SYSTEM_EVENT+++
desc V$SYSTEM_EVENT

prompt +++V$SYSTEM_FIX_CONTROL+++
desc V$SYSTEM_FIX_CONTROL

prompt +++V$SYSTEM_PARAMETER+++
desc V$SYSTEM_PARAMETER

prompt +++V$SYSTEM_PARAMETER2+++
desc V$SYSTEM_PARAMETER2

prompt +++V$SYSTEM_PARAMETER4+++
desc V$SYSTEM_PARAMETER4

prompt +++V$SYSTEM_WAIT_CLASS+++
desc V$SYSTEM_WAIT_CLASS

prompt +++V$SYS_OPTIMIZER_ENV+++
desc V$SYS_OPTIMIZER_ENV

prompt +++V$SYS_REPORT_REQUESTS+++
desc V$SYS_REPORT_REQUESTS

prompt +++V$SYS_REPORT_STATS+++
desc V$SYS_REPORT_STATS

prompt +++V$SYS_TIME_MODEL+++
desc V$SYS_TIME_MODEL

prompt +++V$TABLESPACE+++
desc V$TABLESPACE

prompt +++V$TEMPFILE+++
desc V$TEMPFILE

prompt +++V$TEMPORARY_LOBS+++
desc V$TEMPORARY_LOBS

prompt +++V$TEMPSTAT+++
desc V$TEMPSTAT

prompt +++V$TEMPUNDOSTAT+++
desc V$TEMPUNDOSTAT

prompt +++V$TEMP_CACHE_TRANSFER+++
desc V$TEMP_CACHE_TRANSFER

prompt +++V$TEMP_EXTENT_MAP+++
desc V$TEMP_EXTENT_MAP

prompt +++V$TEMP_EXTENT_POOL+++
desc V$TEMP_EXTENT_POOL

prompt +++V$TEMP_PING+++
desc V$TEMP_PING

prompt +++V$TEMP_SPACE_HEADER+++
desc V$TEMP_SPACE_HEADER

prompt +++V$THREAD+++
desc V$THREAD

prompt +++V$THRESHOLD_TYPES+++
desc V$THRESHOLD_TYPES

prompt +++V$TIMER+++
desc V$TIMER

prompt +++V$TIMEZONE_FILE+++
desc V$TIMEZONE_FILE

prompt +++V$TIMEZONE_NAMES+++
desc V$TIMEZONE_NAMES

prompt +++V$TOPLEVELCALL+++
desc V$TOPLEVELCALL

prompt +++V$TRANSACTION+++
desc V$TRANSACTION

prompt +++V$TRANSACTION_ENQUEUE+++
desc V$TRANSACTION_ENQUEUE

prompt +++V$TRANSPORTABLE_PLATFORM+++
desc V$TRANSPORTABLE_PLATFORM

prompt +++V$TSDP_SUPPORTED_FEATURE+++
desc V$TSDP_SUPPORTED_FEATURE

prompt +++V$TSM_SESSIONS+++
desc V$TSM_SESSIONS

prompt +++V$TYPE_SIZE+++
desc V$TYPE_SIZE

prompt +++V$UNDOSTAT+++
desc V$UNDOSTAT

prompt +++V$UNIFIED_AUDIT_RECORD_FORMAT+++
desc V$UNIFIED_AUDIT_RECORD_FORMAT

prompt +++V$UNIFIED_AUDIT_TRAIL+++
desc V$UNIFIED_AUDIT_TRAIL

prompt +++V$UNUSABLE_BACKUPFILE_DETAILS+++
desc V$UNUSABLE_BACKUPFILE_DETAILS

prompt +++V$VERSION+++
desc V$VERSION

prompt +++V$VPD_POLICY+++
desc V$VPD_POLICY

prompt +++V$WAITCLASSMETRIC+++
desc V$WAITCLASSMETRIC

prompt +++V$WAITCLASSMETRIC_HISTORY+++
desc V$WAITCLASSMETRIC_HISTORY

prompt +++V$WAITSTAT+++
desc V$WAITSTAT

prompt +++V$WAIT_CHAINS+++
desc V$WAIT_CHAINS

prompt +++V$WALLET+++
desc V$WALLET

prompt +++V$WLM_PCMETRIC+++
desc V$WLM_PCMETRIC

prompt +++V$WLM_PCMETRIC_HISTORY+++
desc V$WLM_PCMETRIC_HISTORY

prompt +++V$WLM_PC_STATS+++
desc V$WLM_PC_STATS

prompt +++V$WORKLOAD_REPLAY_THREAD+++
desc V$WORKLOAD_REPLAY_THREAD

prompt +++V$XML_AUDIT_TRAIL+++
desc V$XML_AUDIT_TRAIL

prompt +++V$XSTREAM_APPLY_COORDINATOR+++
desc V$XSTREAM_APPLY_COORDINATOR

prompt +++V$XSTREAM_APPLY_READER+++
desc V$XSTREAM_APPLY_READER

prompt +++V$XSTREAM_APPLY_RECEIVER+++
desc V$XSTREAM_APPLY_RECEIVER

prompt +++V$XSTREAM_APPLY_SERVER+++
desc V$XSTREAM_APPLY_SERVER

prompt +++V$XSTREAM_CAPTURE+++
desc V$XSTREAM_CAPTURE

prompt +++V$XSTREAM_MESSAGE_TRACKING+++
desc V$XSTREAM_MESSAGE_TRACKING

prompt +++V$XSTREAM_OUTBOUND_SERVER+++
desc V$XSTREAM_OUTBOUND_SERVER

prompt +++V$XSTREAM_TABLE_STATS+++
desc V$XSTREAM_TABLE_STATS

prompt +++V$XSTREAM_TRANSACTION+++
desc V$XSTREAM_TRANSACTION

prompt +++V$XS_SESSIONS+++
desc V$XS_SESSIONS

prompt +++V$XS_SESSION_NS_ATTRIBUTE+++
desc V$XS_SESSION_NS_ATTRIBUTE

prompt +++V$XS_SESSION_ROLE+++
desc V$XS_SESSION_ROLE

prompt +++V$_LOCK+++
desc V$_LOCK

prompt +++V$_LOCK1+++
desc V$_LOCK1

prompt +++V$_SEQUENCES+++
desc V$_SEQUENCES

spool off
exit
